### ISSUE TITLE
Clarification on box corners and geometry corners

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#112]
Consider this 2D snippet
```fortran
type(amrex_box) :: domain
type(amrex_geometry) :: geom
domain = amrex_box([1,1], [10,10])
call amrex_geometry_build(geom, domain)
```
where
```
geometry.prob_lo = 0.0  0.0  0.0
geometry.prob_hi = 1.0  1.0  1.0
```
When I visualize the data on the associated multifab (visit) I expect to see a 10x10 mesh covering the unit square [0,1]^2, but instead the rendered domain is [0.1, 1.1]^2.  I get what I expect if I instead do
```fortran
domain = amrex_box([0,0], [9,9])
```
It seems the geometry (or plotting code?) assumes the box indices are 0-based.  Is this a mistake or intentional?  My sense of a box is it is an _arbitrary_ rectangular section of index space (user's choice) and it ought to be possible to associate any box with a given rectangular geometry.

**Comment by drummerdoc** [comment]
Hey Neil, I'm just guessing, but that certainly seems to be a problem within Visit, or simply interpretation.

MultiFab's are not inherently associated with a grid spacing/geometry information.  They live in pure index space.  Plotfiles are a mechanism to give the MultiFab a physical context.  If indeed you are simply trying to visualize a MultiFab, there is no reason for VisIt to expect that you've provided information for the grid-spacing and domain origin.  My guess is that the VisIt authors just made something up that seemed reasonable.  

You can either write the MultiFab into a plotfile, or ignore the physical coordinates of that plotting software.

**Comment by nncarlson** [comment]
Hi Marc, I'm not sure I understand you.  I am writing a multifab with `amrex_write_plotfile` which also requires the geometry as an argument.  So it seems to me that there ought to be enough info in the plotfile in order to give the multifab the correct physical context.  So perhaps it is a problem with the visit reader.  I'll see if I can't get amrvis compiled and give it a try; I had the impression until reading the user manual today that visit was your primary viz tool.

**Comment by asalmgren** [comment]
Neil -- are you writing a plotfile by calling one of the amrex routines?  If yes, then the index space of the geometry is definitely written there as you said, so if the geometry starts at (1,1) rather than (0,0) and the MultiFab starts at (1,1) and the domain is [0.0:1.0] then you are absolutely correct, the plotting routine should recognize the MultiFab starts at physical location 0.   So in that case it must be the case that Visit somewhere assumes the domain always starts at (0,0).   Visit know how to read the format so it must be able to read the geometry data but we've never explicitly asked them if they use it -- that's worth doing.

I just wanted to confirm that you're using that one as opposed to a "homegrown" writePlotFile.  

Amrvis is in fact under our control since we built it so if it does the same thing we can definitely fix it -- please let us know!

**Comment by zingale** [comment]
at the risk of information overload, many of us have switched to yt from visit: http://yt-project.org/
it knows how to deal with AMReX data.

**Comment by asalmgren** [comment]
Mike -- do you know if anyone has actually tested a domain that didn't start at (0,0)?

**Comment by zingale** [comment]
I don't know the answer to that.

**Comment by nncarlson** [comment]
Ann, Yes, I'm using one of the amrex Fortran routines `amrex_write_plotfile`

I've built amrvis2d, but I'm not sure I'm going to be able to do much with it anytime soon (seems I need to figure out how to generate a palette file).  I also don't see anything about spatial coordinates there.  Looks interesting though.  I'll give yt a try next.

But this issue is mostly an irritation to me that I can overlook now that I'm fairly confident where the problem is, and not some fundamental misunderstanding  I have with the way amrex works.

**Comment by WeiqunZhang** [comment]
My suggestion is you should have the domain index start with 0.  Even if visualization tools can display correctly when the index starts with 1, you should still have the domain index start with 0.

Consider this as a limitation of AMReX.  The problem is a box like [1,10] is considered `uncoarsenable` in AMReX.  Coarsening it would result in [0,5].  If the coarsened box is refined again, we get [0,10], different from the original box.  This would create a lot of problems.

**Comment by WeiqunZhang** [comment]
This doesn't mean we cannot have a box with index starting with an odd number.  But for the whole domain, it is safer to have index start with zero, especially when there are AMR and multigrid.

**Comment by nncarlson** [comment]
@WeiqunZhang thanks for the clarification; I'll follow your advice.  And thanks all for your comments on this labor day!
