### ISSUE TITLE
Questions about setting the Dirichlet BC for finer level

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#147]
Hello all,

I am now developing an staggered in-compressible fluid solver based on amrex-frame. On level 0, I used multigrid solver for solving Poisson euqation. Then, I interpolated pressure from level 0 to level 1 for filling ghost cell on level (like the purple star in the fig). However, **I do not know how to set up the these interpolated ghost value as the Dirichlet boundary condition for multifab on level 1.**  

![image](https://user-images.githubusercontent.com/30739800/31700988-bc233b06-b392-11e7-9d13-ddcb7cdef2d2.png)

In the AMReX_Docs, a function:
void amrex::BndryData::setValue | ( | Orientation | face,
  |   | int | n,
  |   | Real | val
  | )
can only set a fixed value for Dirichlet BC, not the interpolated value. I noticed this function because the multi-grid solver in Old Tutorials use this function to set up the Dirichlet Boundary condition.

Can anyone give me some suggestions? Maybe I should use other functions.

Thanks a lot.

**Comment by ajnonaka** [comment]
Hi,

Have you actually filled the ghost cells marked with STARS using a FliiPatch routine?  If you did, the values in the STARS represent spatially interpolated values to that ghost cell center.  So if you want these values to represent the value along the grid boundary that is not the correct interpretation.  In many cases if we want to do something, e.g. take a face-centered gradient from cell-centered data at level 1, we use the same stencil everywhere, knowing that the ghost values represent extensions of pressure to the ghost cell-center.

Andy

**Comment by drummerdoc** [comment]
How did you do the interpolation?  Why did you decide to interpolate to cell-centers (assuming you really wanted p on faces)?  What routines did you use/write to do this, and can they be modified to do what you really want instead?

Also, BndryData has an access function, operator[] that returns a FabSet, and FabSet has an access function that returns an FArrayBox.  Assuming that you can get the values you want to enforce as Dirichlet values to the correct location, you can set them at each index using these functions. The setValue function you mention is provided because it tends to be particularly simple/useful (for homogeneous BCs, for example).

**Comment by ruihai0925** [comment]
@ajnonaka Thanks for your hints. I will answer your question.

Q: Have you actually filled the ghost cells marked with STARS using a FliiPatch routine?

A: Yes, I interpolated pressure value on level 0 to level 1 by using FillPatch routine with a cell_cons_interp. Also, to explain @drummerdoc , pressure is cell-centered in my definition, not face centered. I plan to use these purple-star interpolated values as ghost cell values for Dirichlet Boundary Condition. I mean, I will not change these values when solving Poisson equation on level 1. Maybe. the range and edge of level 1 is somewhat misleading.

Also, I am now deciding to choose one interpolation schemes for all variables (e.g. pressure, velocities), maybe it is your meaning about same stencil. I am not sure if I understand it right.

**Comment by ruihai0925** [comment]
@drummerdoc Thanks for your answer. Here are my thoughts about your questions.

Q:  What routines did you use/write to do this, and can they be modified to do what you really want instead?

A: Small codes section:

MultiFab Sborderp(grids[lev], dmap[lev], S_newp.nComp(), num_grow);
FillPatchp(lev, time, Sborderp, 0, Sborderp.nComp());

I defined a temporary mf Sborderp and use FillPatchp to fill data. Are there some suggestions?

I will try to find the access functions interface as you said.  They maybe very helpful. 

Also, **another question is that I choose mg solver for level solving, how about the composite solver?** In Almgren, Ann S., et al. JCP paper, a mulilevel solver for composite hierarchy is used to make velocities divergence free in the whole field. Can we find similiar examples from amrex package to solve Poisson equation over composite grid hierarchy for cell-centered pressure?

Thanks for your kindness.

**Comment by WeiqunZhang** [comment]
Because the interpolated pressure from level 0 is used as Dirichlet boundary for level 1 implicit solve, you don't want to use `FillPatch` with `cell_cons_interp`.  The interpolation would involve coarse cells covered by fine cells.  Instead you can use `MacBndry`.   For example,

https://github.com/AMReX-Codes/IAMR/blob/master/Source/MacProj.cpp#L347

For level > 0 (i.e., fine level), the coarse data are copied into a `BndryRegister`, which in turn is passed to `MacBndry::setBndryValue` function from `MacBndry`'s base class `InterpBndryData`.  That function will interpolate the coarse data in the directons parallel to the coarse/fine interface, but not in the face normal direction.    So the location of the data is `0.5 * dx_c` away from the c/f face, where `dx_c` is coarse cell size.  If you use AMReX's `C_CellMG`, you can just pass the `MacBndry` object to the `LinOp` object.  It knows how to treat the boundary in the linear solver.

**Comment by ruihai0925** [comment]
Hello all,

I still have a question about **how to interpolate the ghost cell value of finer level from coarser level.** 

As @WeiqunZhang said, I learned the codes in MacProj.cpp and knew a little about the BndryRegister and MacBndry class. Yet, it seems these classes are used for providing the tangential interpolation to the c/f interface and the level solver. I have not found the normal interpolation to the c/f interface, thus I can not get the ghost cell values of higher levels (e.g. the squares and triangles in the FIG.3.(b) JCP paper).

Also, as Andy @ajnonaka said, I also reread the "FillPatch" subroutine. To my understanding, this subroutine fills all cells, valid and ghost with space-time interpolation. It is usually used when a new finer level appears after regridding, so that we need to generate the variables on the newest level. Yet, what I want now is not interpolating to all cells, but only the values of cell-centered ghost cells. I mean, I already have the value of interior cells of finer levels. 

My aim is to do some operations (e.g. divergence) on finer levels with the cell centered ghost cell values on finer levels, not to do the level solving.

Thanks, all.

Ruohai

**Comment by drummerdoc** [comment]
If you look in `Src/LinearSolvers/MLMG` and search for `applybc`, that is where the normal interpolation is done.  If you need help understanding the code, let me know.

**Comment by WeiqunZhang** [comment]
> My aim is to do some operations (e.g. divergence) on finer levels with the cell centered ghost cell
> values on finer levels, not to do the level solving.

You could set up MLMG and your linear operator as usual.  Then instead of calling `MLMG::solve`, you could call `MLMG::apply(const Vector<MultiFab*>& out, const Vector<MultiFab*>& in)` to compute `out = L(in)`.  If MLMG is only used for this, not for an actual solve, you could  turn off multigrid coarsening by constructing a MLLinOp object with an appropriate LPInfo object (e.g., with `LPInfo().setMaxCoarseningLevel(0)`).  Also note after `apply` is called, MulitFabs `in` will have their ghost cells filled properly with the interpolation explained by @drummerdoc in his last comment.  So you could use them for some additional computations.
