### ISSUE TITLE
Fortran external dirichlet BC usage

### ISSUE THREAD

**Issue by pedro-ricardo** [AMReX-Codes/amrex#1735]
Hello there.
I can't seem to find in the examples how to set a external dirichlet (`amrex_bc_ext_dir`) in Fortran.
The examples use the `amrex_filcc` that will fill the other BCs but not `amrex_bc_ext_dir` as expected.
```f90
call amrex_mfiter_build(mfi, mf, tiling=.false.)
do while(mfi%next())
    p => mf%dataptr(mfi)
    if (.not. geom%domain%contains(p)) then
        plo = lbound(p)
        phi = ubound(p)
        call amrex_filcc(p, plo, phi,        & 
            geom%domain%lo, geom%domain%hi,  & 
            geom%dx,                         &
            geom%get_physical_location(plo), &
            lo_bc, hi_bc)
        ! Maybe insert it here ? like `call my_ext_dir (...)`
    end if
end do
```
If I missed a Fortran tutorial for that, can someone point me to it? Otherwise a brief explanation on how to set it would be fine.

I suppose that it will be in the same loop as `amrex_filcc` above, but I lack the knowledge of which `amrex_` intrinsic variables may help me in finding the face that is touching the boundary or other relevant info that can be used in here.

Thanks

**Comment by pedro-ricardo** [comment]
In this case I've noticed that `tiling=.false.` is used
Is it for better performance since this functions will only loop through box faces?

Just another thing .. do I really need one `amrex_physbc_proc` kind of function for each variable I own?
In order to allow variables with different BCs?

**Comment by WeiqunZhang** [comment]
Yes, tiling is turned off because we are working on cells outside the physical domain only.

Yes, you can insert a call to your own procedure after `amrex_filcc1.  `geom%domain`, `plo`, and `phi` have all the information you need to figure out the boundary information.

You can use one `amrex_physbc_proc` function for all the variables, and it's better than using one for each variable.  Note that one of the arguments to `amrex_fillpatch` is for the number of components.  You could use one `amrex_physbc_proc` for one variable.  But then you will have to call `amrex_fillpatch` multiple times.

**Comment by pedro-ricardo** [comment]
Thank you!
