### ISSUE TITLE
question about the Advection_AmrCore example

### ISSUE THREAD

**Issue by wangzhezhe** [AMReX-Codes/amrex#1806]
Hello, 

I tried to run the `Tutorials/Amr/Advection_AmrCore` example with MPI (AMReX_MPI is set as ON), but it seems that the code is executed on only one process:

```
 $srun -C haswell -l -n 2 ./example/amrexadvecation/amrAdvecation ~/cworkspace/src/Gorilla/example/amrexadvecation/Exec/inputs
0: MPI initialized with 2 MPI processes
0: MPI initialized with thread support level 0
0: AMReX (21.02-17-g932836ad422a) initialized
0: Successfully read inputs file ... 
0: Writing plotfile plt00000
0: 
0: Coarse STEP 1 starts ...
0: [Level 0 step 1] ADVANCE with time = 0 dt = 0.01093983378
0: [Level 0 step 1] Advanced 32768 cells
0: [Level 1 step 1] ADVANCE with time = 0 dt = 0.005469916891
0: [Level 1 step 1] Advanced 65536 cells
0: [Level 2 step 1] ADVANCE with time = 0 dt = 0.002734958446
0: [Level 2 step 1] Advanced 204800 cells
0: [Level 2 step 2] ADVANCE with time = 0.002734958446 dt = 0.002734958446
0: [Level 2 step 2] Advanced 204800 cells
0: [Level 1 step 2] ADVANCE with time = 0.005469916891 dt = 0.005469916891
0: [Level 1 step 2] Advanced 65536 cells
0: [Level 2 step 3] ADVANCE with time = 0.005469916891 dt = 0.002734958446
0: [Level 2 step 3] Advanced 204800 cells
0: [Level 2 step 4] ADVANCE with time = 0.008204875337 dt = 0.002734958446
0: [Level 2 step 4] Advanced 204800 cells
0: Coarse STEP 1 ends. TIME = 0.01093983378 DT = 0.01093983378 Sum(Phi) = 33797.09926
......
```
You could see that only the rank 0 process output the information even if there are 2 MPI processes. I'm curious if this example is designed for the MPI case, or is there configuration I should set? Thanks a lot for your help!

**Comment by maximumcats** [comment]
Hi @wangzhezhe, this is intentional behavior and relatively standard among MPI-based codes. It would get very noisy if many MPI ranks were all writing to stdout with information about the progress of the simulation, and this example (as well as most other AMReX use cases) runs under the assumption that the ranks are all participating in the same advance, so having multiple ranks print out information would be redundant.

From a code perspective, you can see that these print statements in `AmrCoreAdv.cpp` uses `amrex::Print()` which only prints out the information on one rank. If you wanted every rank to do it, you could change that to `std::cout`, but it would not be adding any new information.

**Comment by wangzhezhe** [comment]
Thanks a lot for the information! @maxpkatz  I just want to check if the process with the more mesh refinement options takes more time to do the simulation computation

**Comment by wangzhezhe** [comment]
Thanks a lot for the information!
