### ISSUE TITLE
Problem with macros in Fortran files when using AMReX as a lib. 

### ISSUE THREAD

**Issue by atmyers** [AMReX-Codes/amrex#1893]
When setting up CI for the amrex-tutorials repo, I noticed that the `BL_SPACEDIM` seems not to be defined when building Fortran files: https://github.com/AMReX-Codes/amrex-tutorials/pull/3/checks?check_run_id=2173776394

The problem seems to be that the definitions in `AMReX_Config.H` are not being exposed to Fortran. 

I think we never noticed this before because our tests with Fortran mains did not use amrex as an external lib.

**Comment by mic84** [comment]
I think we never noticed this because we don't enable ``AMReX_FORTRAN_INTERFACES`` in the CI. For CMake, this issue affect superbuild and standalone modes, since the config file is used in both cases.

I tried to including ``AMReX_Config.H`` in the affected Fortran files and it fixes the problem. @WeiqunZhang what do you think about it?

**Comment by WeiqunZhang** [comment]
This does not appear to be an issue in amrex.  The fortran code could include `AMReX_SPACE.H`, which is safe to be included by Fortran, if they need macro.  Or they could the `amrex_fort_module`.

**Comment by WeiqunZhang** [comment]
I think we should just modify the tutorial code.

**Comment by WeiqunZhang** [comment]
Including `AMReX_Config.H` is also fine, but `AMReX_SPACE.H` provides `AMREX_D_DECL` etc. to Fortran too.

**Comment by WeiqunZhang** [comment]
`AMREX_SPACE.H` was used extensively in the BoxLib days by Fortran.

**Comment by atmyers** [comment]
Sounds good, we will fix this on the tutorials side by including `amrex_fort_module`.
