### ISSUE TITLE
Does AMRex support impilicit solver 

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#197]
Dear sir:
     I want to sue AMRex to solve convection diffusion equations in an implicit way.  Does AMRex support this.
    I didn't find any information about this in the user guide
Regards

**Comment by ajnonaka** [comment]
Yes, the interfaces for linear solvers has been redesigned and exist in the development branch (to be merged into master branch next month).  There is no documentation yet (coming soon, I hope to write some this week) but there are a few tutorials.

We support two solvers where the solution, 'phi', is cell-centered or nodal.  For each case you can solve on a single level (using essentially Dirichlet conditions supplied from coarser levels or physical boundary conditions), or you can do a multilevel composite solve on a subset of AMR levels (or even all the AMR levels).

The tutorial amrex/Tutorials/LinearSolvers/ABecLaplacian_C shows how to call the cell-centered solver.  The tutorial amrex/Tutorials/Basic/HeatEquation_EX3_C shows how to solve the implicit heat equation using the cell-centered solver.  Here an "ABecLaplacian" has the form "(acoeff * A - bcoeff * div B grad) phi = RHS", where acoeff, bcoeff are scalars, A, B, and RHS are MultiFabs.  For the cell-centered solver, A and RHS are cell centered, and B is an array of face-centered MultiFabs since "B grad phi" lives on faces, and the divergence lives on cell-centers.

Hope this is enough to get you started until we get documentation together.
