### ISSUE TITLE
CUDA derive functions are not launched from AMReX in C++

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#222]
Currently we are forced to launch AmrLevel::derive functions in a separate wrapper script, because the DeriveFunc is a typedef rather than a true function handle, so nvcc will not compile it as a \_\_global\_\_ function. We should find a way around this so that the user does not have to manually write their own kernel launches.

**Comment by maxpkatz** [comment]
The same issue applies to BndryFunc, so the user also has to write their own kernel launches for ghost zone fill routines.

**Comment by WeiqunZhang** [comment]
@maxpkatz what's you current thought on this?

A new derive function type has been add.

```
typedef void (*DeriveFuncFab) (const amrex::Box& bx, amrex::FArrayBox& derfab, int dcomp, int ncomp,
                               const amrex::FArrayBox& datafab, const amrex::Geometry& geomdata,
                               amrex::Real time, const int* bcrec, int level);
```

An example of using the new derive function can be found at https://github.com/AMReX-Codes/amrex/blob/master/Tutorials/GPU/CNS/Source/CNS_setup.cpp#L134 and https://github.com/AMReX-Codes/amrex/blob/master/Tutorials/GPU/CNS/Source/CNS_derive.cpp.

For `BndryFunc`, we have added new capabilities.  An example can be found at  https://github.com/AMReX-Codes/amrex/blob/master/Tutorials/GPU/CNS/Source/CNS_setup.cpp#L121 and https://github.com/AMReX-Codes/amrex/blob/master/Tutorials/GPU/CNS/Source/CNS_bcfill.cpp.  Currently when `StateDescriptor::BndryFunc` is created with the new interface, one also needs to call `setRunOnGPU(bool)` so that we don't have host/device synchronization issues.  The interface could be improved so that the function passed to `BndryFunc` carries the information itself and the call to `setRunOnGPU` can then be eliminated.

**Comment by maximumcats** [comment]
Closing as this has been resolved.
