### ISSUE TITLE
Definition of geom in non-periodic EXT_DIR condition

### ISSUE THREAD

**Issue by rsiddu0511** [AMReX-Codes/amrex#2317]
In an attempt to solve a Laplacian Equation solver, I used this line from HeatEquation_EX2_C

`define(domain,real_box,CoordSys::cartesian,is_periodic.data());`

But I am getting the following error:

`error: no matching function for call to ‘amrex::Geometry::define(amrex::Box&, amrex::RealBox&, amrex::CoordSys::CoordType, int*)'`

Sorry if this is something trivial but it would be of great help if anybody can give some hints regarding what significance `is_periodic.data()` carries.

Thanking you in advance

**Comment by atmyers** [comment]
`is_periodic` carries `AMREX_SPACEDIM` integers that are `0` if the domain is non-periodic in that direction and `1` if it is. `is_periodic.data()` returns to the pointer to the start of the memory where those numbers live, which is what what the `define` method of `amrex::Geometry` [expects](https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Geometry.html#aeba60991848a022ff91863c7b6af0de8).

I think the compilation error is because `define` takes a `RealBox*` not a `RealBox&`, i.e. you should do

```
define(domain,&real_box,CoordSys::cartesian,is_periodic.data());
```

**Comment by rsiddu0511** [comment]
Alright @atmyers sir, now I am getting it. Thank you once again for taking time to clarify my query.
