### ISSUE TITLE
'flux registers' for edge-centered EMFs?

### ISSUE THREAD

**Issue by WeiqunZhang** [AMReX-Codes/amrex#2512]
### Discussed in https://github.com/AMReX-Codes/amrex/discussions/2511

<div type='discussions-op-text'>

<sup>Originally posted by **BenWibking** December  2, 2021</sup>
Hi,

We are planning to implement face-centered MHD in Quokka. Is there a 'flux register' to do the correction at coarse-fine interfaces of edge-centered EMFs in AMReX? In Chombo, this can be accomplished with [`LevelFluxRegisterEdge`](http://colella.lbl.gov/Manuals/CHOMBO-RELEASE-3.3/classLevelFluxRegisterEdge.html), which has a similar API to `YAFluxRegister`.

Example:
<img width="372" alt="Screen Shot 2021-12-03 at 2 14 21 PM" src="https://user-images.githubusercontent.com/1781919/144539019-11d98c91-9ac2-4ed6-a347-96a6a0b97b0a.png">

There are a number of corner cases (see panels a-d copied below). (In [Athena++](https://arxiv.org/pdf/2005.06651.pdf), this step is also done at all shared edges between grids on the same resolution level in order to avoid roundoff errors, but it's not currently clear whether this will be necessary.)

<img width="855" alt="Screen Shot 2021-12-03 at 2 15 11 PM" src="https://user-images.githubusercontent.com/1781919/144539027-d413aabc-94a6-4e09-8d9c-a4f3539f9652.png"></div>

**Comment by BenWibking** [comment]
Is this something that is likely to be available on a ~few months timescale? The reason I ask is because Mark (@markkrumholz) and I are advising a PhD student on implementing method-of-lines MHD in Quokka and whether this will be available in AMReX would significantly affect the direction we go.

I see that there is now a CTU+MHD implementation in Castro. This could be useful for Castro if subcycling AMR is desired for that. In principle, FLASH could also use this, although they might instead average down the edges before doing the update.

**Comment by WeiqunZhang** [comment]
We will give this a push in the next few weeks.

**Comment by BenWibking** [comment]
Ok, thanks for the update!

**Comment by BenWibking** [comment]
@WeiqunZhang Just wanted to follow up on this.

**Comment by WeiqunZhang** [comment]
@BenWibking Thanks for reminder!
