### ISSUE TITLE
Stencil for cut cell and enforcing boundary conditions on embedded body surface (EB_CNS Tutorial)

### ISSUE THREAD

**Issue by ashwathsv** [AMReX-Codes/amrex#2565]
This is more a question than an issue: 

1) How are the boundary conditions enforced on the embedded boundary surface? For example, if we need to enforce a no-slip/no-penetration BC on the object surface, do we use a different stencil relative to the rest of the domain? Does the FillPatch routine appropriately fill the ghost cells for the embedded boundary too or does this need to be done separately? It would be very helpful if the specific functions that perform this task are listed.

Thanks in advance.

**Comment by WeiqunZhang** [comment]
In `Tests/EB_CNS/`, the flux on the EB surface is  computed by function `compute_hyp_wallflux` in `Tests/EB/EB_CNS/Source/hydro/CNS_hydro_K.H`.  It solves a Riemann problem with the same density and pressure for the two states.  The normal velocity is reflected at the interface and the transverse velocity is set to zero.

In funciton `CNS::variableSetup` in `Tests/EB_CNS/Source/CNS_setup.cpp`, `eb_mf_cell_cons_interp` is used to set up the StateDataDescriptor.  `eb_mf_cell_cons_interp` is defined in `Src/EB/AMReX_EBMFInterpolater.cpp`.  Because of the interpolater, the FillPatch functions fill cut cells too in a conservative manner.
