### ISSUE TITLE
Prescribing External Dirichlet Values

### ISSUE THREAD

**Issue by jameslehoux** [AMReX-Codes/amrex#264]
Apologies if this seems a simple question but I'm having trouble implementing boundary conditions.

Specifically I'm looking at the Basic/HeatEquation_EX3_C tutorial and trying to follow along with the documentation. 

I can see that there is an IF loop in order to determine the boundary condition type (Neumann, Dirichlet, Periodic) but how do you actually prescribe values? I've selected BCType::ext_dir and am trying to change the value used to fill the ghost cells.

I know in the documentation it mentions 'it is the user's responsibility' but is there a simple example of how to change them? 

Thank you in advance,
James

**Comment by ajnonaka** [comment]
Hi James,

First I want to point out that the Dirichlet boundary conditions don't work in this example yet (I just tested it) but will explain to you here how to implement them.

Keep in mind that for the linear solvers (since this example uses an implicit discretization of the heat equation), for Dirichlet conditions, the value that sits in the ghost cell will represent the Dirichlet value that physically lives on the boundary (NOT the value extrapolated to the ghost cell-center location).

So what this means is you need a loop that sets the value in the ghost cells to the Dirichlet value.  This is already "built-in" to amrex to some extent--- In advance.cpp there is a call to FillDomainBoundary().  Tracing through the code, here's where this leads:

advance.cpp:FillDomainBoundary()

AMReX_BCUtil.cpp:FillDomainBoundary()

AMReX_filcc_mod.F90:amrex_fab_filcc()

AMReX_filcc_mod.F90:amrex_filccn()

This subroutine amrex_filccn() is the one that fills ghost cells.  However you will notice that for all instances of "amrex_bc_ext_dir" (Dirichlet) there is currently a "do nothing" comment.  What you need to do is write a loop to fill the ghost cells here.  Keep in mind the integer array "bc" here refers to the (direction, lohi_side, component) so you may need to write multiple loops (one for each face of the domain)

I suggests just copying in the code for the amrex_bc_foextrap case immediately below each case of amrex_bc_ext_dir case, but change the values to the Dirichlet values you need.  Note the amrex_bc_foextrap case is an example of simply coping the interior value into the ghost cell (i.e., a first-order homogeneous Neumann boundary condition)

**Comment by WeiqunZhang** [comment]
If the Dirichlet value is constant, you can simply call `phi_old.setDomainBndry(val, 0, 1, geom)` instead of `FillDomainBoundary`.   If not, I suggest you make a local copy of function `FillDomainBoundary` from `amrex/Src/Base/AMReX_BCUtil.cpp` and rename it.  Then in your own `FillDomainBoudary` like function, replace `amrex_fab_filcc` with your own function for filling Dirichlet.

Also note that for Neumann BC, the linear solver only supports homogeneous Neumann.  And one does not need to call `armex_fab_filcc` to fill homogeneous Neumann for the linear solver, because the solver will do it anyway.

There is also no need to call `phi_old.FillBoundary` in `advance` for the similar reason that the linear solver's `setlevelBC` function will only read Dirichlet boundary values and ignore all other data.

**Comment by jameslehoux** [comment]
Aha! That's perfect thank you both very much for your help.
