### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by nmnobre** [AMReX-Codes/amrex#2978]
Hi,

I'm a bit confused so I'll try my best to not make a mess of this...

1) When compiling with the Intel classic compilers, CMake uses -O3 whereas the Make uses -O2, both for non-debug builds. Can you please clarify why this is the case?

2) When compiling with the Intel classic compilers, for a debug build, CMake uses the flags in `AMReXFlagsTargets.cmake` for both the classic and llvm Intel compilers. Is this on purpose? I'm a bit of a noob in CMake so I don't really know how these flags are picked up in the first place.

3) When compiling an application that uses AMReX, I can't seem to be able to make `AMReX::Flags_CXX` work in my `CMakeLists.txt`:
    ```
    # CMake minimum version
    cmake_minimum_required (VERSION 3.15)
    
    # Project name
    project(foobar)
    
    # All cpp source files
    file(GLOB_RECURSE src_files *.cpp)
    
    # Import AMReX settings and targets
    find_package(AMReX REQUIRED)
    
    # Generate obj files
    add_executable(${PROJECT_NAME} ${src_files})
    target_link_libraries(${PROJECT_NAME} AMReX::amrex AMReX::Flags_CXX)
    ```
    No compilation flags are added. However, using `-DCMAKE_BUILD_TYPE=<build_type>` does add the compilation flags used to compile AMReX no matter if `AMReX::Flags_CXX` is present or not... Curiously, if `<build_type>` is set to `Debug` and I use the Intel classic compilers, then only the flags for the classic compiler in `AMReXFlagsTargets.cmake` are picked up (unlike what happens above when compiling AMReX itself). Is this the intended behaviour? It'd be nice if there was an option to compile an application with the same compilation flags that were used to compile AMReX, is this possible with CMake?

Cheers,
-Nuno

**Comment by WeiqunZhang** [comment]
1. The GNU Make system uses `-O2` because of history.  In the past (~ 10 years ago), the Intel compiler seemed to be very buggy when `-O3` was used.  Not sure about the situation now, but we have never bothered to change the default. Anyway, the user should feel free to change it to `-O3`.  In the CMake system, I think the flag is chosen by CMake not by AMReX.

As for other CMake questions, @ax3l, could you please answer?

**Comment by nmnobre** [comment]
Hi,

1. That makes sense. And I think you're right about the flag being automatically picked by CMake, at least I couldn't find a matching line on AMReX's sources when I looked. Thanks :)

**Comment by ax3l** [comment]
Hi @nmnobre,

1. The CMake options are also historic defaults and I am not aware of issues with `-O3` for our supported compilers at the moment, which is default for `Release`. Their defines are [in this directory](https://gitlab.kitware.com/cmake/cmake/-/tree/master/Modules/Compiler), e.g., the [Classic Intel Compiler defaults](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.23.4/Modules/Compiler/Intel.cmake#L25) for `Release`.
2. Are we really? [Classic Intel](https://github.com/AMReX-Codes/amrex/blob/22.10/Tools/CMake/AMReXFlagsTargets.cmake#L76-L78) and IntelLLVM (oneAPI) are [separate flags](https://github.com/AMReX-Codes/amrex/blob/22.10/Tools/CMake/AMReXFlagsTargets.cmake#L91-L93). Did you remove your `build/` directory when you switched the compilers for testing? (The `CMakeCache.txt` file otherwise does not search for new defaults.)
3. Try the "new" (CMake 3.0+) syntax of CMake in `target_link_libraries`:
```cmake
# ...
target_link_libraries(${PROJECT_NAME} PUBLIC AMReX::amrex AMReX::Flags_CXX)
```
The `AMReX::amrex` target will carry its own `PUBLIC` dependencies into your targets.
Extra targets such as `AMReX::Flags_CXX` are [not forwarded by default](https://github.com/AMReX-Codes/amrex/blob/22.10/Src/CMakeLists.txt#L49-L52) and only used when AMReX itself is built. A better syntax in last link would be `PRIVATE`, which would look less confusing (and stay the same for superbuilds and separate builds).

**Comment by ax3l** [comment]
Small CMake notes on your snippet:
- no need to call your executable target the same as your project. You can create multiple libs and executables with all their own names
- consider using modern CMake, 3.20+, for optimal CUDA support
- avoid globbing `.cpp` files via `file(GLOB_RECURSE ...)`, which will slow down and confuse some IDEs you might work with, because they have to research your file system every time something changes. Instead, consider adding them manually, example:
  - https://github.com/ECP-WarpX/impactx/blob/22.10/CMakeLists.txt#L211-L212
  - https://github.com/ECP-WarpX/impactx/blob/development/src/CMakeLists.txt#L1-L12

```cmake
# CMake minimum version: recommending 3.20+ for modern CUDA support
cmake_minimum_required (VERSION 3.20)

# Project name
project(foobar)

# Find Dependencies
find_package(AMReX REQUIRED)

# Build an executable application
add_executable(myfabulousapp)

# Add sources
target_sources(myfabulousapp
  PRIVATE
    src/main.cpp
    src/helper.cpp
)
# Add more sources
target_sources(myfabulousapp
  PRIVATE
    src/more.cpp
    src/evenmore.cpp
)

# Link dependencies
target_link_libraries(myfabulousapp PUBLIC AMReX::amrex AMReX::Flags_CXX)
```

**Comment by ax3l** [comment]
Closing for now as resolved.
Please let us know if you have more questions to this (reopen) or on other topics (new issue or discussion page entry).

**Comment by nmnobre** [comment]
> 2. Are we really? [Classic Intel](https://github.com/AMReX-Codes/amrex/blob/22.10/Tools/CMake/AMReXFlagsTargets.cmake#L76-L78) and IntelLLVM (oneAPI) are [separate flags](https://github.com/AMReX-Codes/amrex/blob/22.10/Tools/CMake/AMReXFlagsTargets.cmake#L91-L93). Did you remove your `build/` directory when you switched the compilers for testing? (The `CMakeCache.txt` file otherwise does not search for new defaults.)

Hi @ax3l, long time no see :), turns out we're just summarising and printing the flags incorrectly, but the flags that are actually used are indeed different between the two compilers. (see #4272)
