### ISSUE TITLE
FillBoundary Improvement Request

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#303]
I am using AMReX framework to simulate LBM flow, and i have tried best to reduce the computation cost/time to the minimum (under 30%). Now, the bottle neck is the fillboundary part (> 60%). Are there any parameters to tune the fillboundary performance, or any suggestion to improve based on HPC configuration?
Till now, my typical simulation case has around 50M points.

**Comment by WeiqunZhang** [comment]
Could you give us more details?  How many boxes do you have?  What's the typical size of boxes?  How many components are there in the MultiFabs?  How many ghost cells?  How many MPI processes (or OMP threads if any) are there?  How do you measure the times?  Is there a load balance issue? ...

**Comment by WeiqunZhang** [comment]
I am not sure I understand the mesh and box information in the text file.  It seems that there are on average 200 Boxes per process and the average Box size is about 16**3 cells.  Is that right?  If so, could you use large Boxes?  Does this have a single level or multiple amr levels?

I am also not sure what your MuliFab like class look like. Is it `FabArray<BaseFab<T>>`, where `T` is something like `struct { double [19]; }`?

Sorry. I don't have Wechat.  I don't have twitter.  I don't have facebook...

**Comment by GumpXiaoli** [comment]
Weiqun:

I use AMReX to do casting flow simulation. The casting model is always very complicated.

Take an example to explain my case. Below is the engine block model. I use four levels to get the mesh. Since i only need the finest level to model, four levels are used to get the mesh number as small as possible (for the same mesh size).

![1](https://user-images.githubusercontent.com/30617135/44941553-b2d76c80-add2-11e8-9fb4-42e5bb27035a.PNG)
![2](https://user-images.githubusercontent.com/30617135/44941555-b5d25d00-add2-11e8-9e8f-69790eb4bbf7.PNG)

I just have a general idea about cluster algorithm. I use below parameters to get the mesh in the above txt file. Only the finest level information is printed in the file.
n_error_buf = 2; blocking_factor = 4; max_grid_size =32; grid_eff = 0.7; n_proper = 1; finest_level = 4;

![3](https://user-images.githubusercontent.com/30617135/44941629-3c3b6e80-add4-11e8-9977-f35a29447959.PNG)
![4](https://user-images.githubusercontent.com/30617135/44941630-3fcef580-add4-11e8-8b0a-e4527e7e56ea.PNG)

I believe i can have better parameters option. Through some effort, i found that it seems better that max_grid_size is set to 64 or 128. But i still don't understand the effect of other parameters.  If possible, can you give some suggestion about tuning these parameters? Or some details about the cluster algorithm?

I define my multifab class as below:
struct LBM19 { Real data[19];};
class FArrayBox_19:public BaseFab<LBM19>;
class MultiFab_LBM19 : public FabArray<FArrayBox_19>;

I don't know whether this will affect the efficience of fillboundary.

Hope to get a better solution.

Many thanks!

                                                                                                                                                  Zhonglin

**Comment by GumpXiaoli** [comment]
Weiqun:

I use AMReX to do flow simulation. The real model is always complicated.

To reduce the mesh number, i use four levels to get the mesh number as small as possible. And i only use the finest level to do the simulation.

I just have a general idea about the cluster algorithm. Below parameters are used to get the mesh in the above txt file.
finest_level=3; n_error_buf = 2; blocking_factor=4; max_grid_size = 32; grid_eff = 0.7; n_proper = 1

I believe better parameters can be chosen to get a better mesh. Through some efforts, it seems good that max_grid_size is set to 64 or 128. Can you give some suggestion for tuning other parameters. Or some details about the cluster algorithm?

I define my MultiFab class as below:
class MultiFab_19 : public FabArray<FArrayBox_19>;
class FArrayBox_19 : public BaseFab<LBM19>;
struct LBM19 { Real data[19];};

Hope to getter a better solution. If you need some more details (for examle: the 3D model, the box structure), i can send you some pictures through personal email.

Many thanks!

													                                Zhonglin

**Comment by WeiqunZhang** [comment]
I would suggest you use max_grid_size = 64 and try to find a sweet spot by varying blocking_factor.  You can try 8, 16, and 32.  I actually saw the pictures in the comment you deleted (?) through email sent by github.   It seems that there are a lot of small 4**3 boxes.  So the ratio of ghost cell volume to valid cell volume is very high.  Using larger blocking factor should help.

For communication, do you always communicate all 19 doubles?  Does FArrayBox_19 have its own versions of `copy`, `copyToMem` and `copyFromMem`?  If not, the template version in `BaseFab` is used.  That is probably slower than if you write your version in Fortran or C (with `restrict` keyword).

FillBoundary only communicates data from valid cells to ghost cells that overlap with each other.   Just curious, how do you fill coarse/fine boundary?

As for AoS vs SoA, I certainly cannot judge which is better for your application running on your computer.  But we usually use SoA because it's arguably better for typical stencil operations.  There is a penalty in vectorization if the memory access doesn't have unit stride for the inner loop.   Depending on the memory access pattern, a common problem for AoS is the data is loaded into a cache line, but only a few bytes are actually being used.

**Comment by GumpXiaoli** [comment]
Larger blocking factor is helpful. However, after testing, i also found that some tagged points will be deleted if we using wrong parameters combination. (For example, n_error_buf = 2; blocking_factor=16) How could i avoid this problem?

Unfortunately, i should always communicate all 19 doubles, which is determined by LBM algorithm. Till now, my FArrayBox_19 uses the template version of copy, copyToMem and copyFromMem in BaseFab. I will try to write my version of these functions.

Since i only use the fineset level for simuation, there is no problem of filling coarse/fine boundary  till now. For multi-level simulation, i think i should write my own interpolation functions. That's my future work.

I am also curious about the tiling technology. I tried to turn on the tiling flag in some cases, but there is no obvious computation efficiency improvement. If possible, I hope to get some suggestion.

Many thanks!

**Comment by asalmgren** [comment]
Points that are tagged should never be deleted by any of the combinations.

What the rest of the parameters control is how many "additional" cells get
refined in order to be able to make boxes that satisfy the requirements,
such as blocking_factor = 8 (means the grid is coarsenable by a factor of
8), etc.

If you can find an example where a point that is tagged in the tagging
routine but does not end up being refined to the finest level, please let
us know and we will fix it!

**Comment by WeiqunZhang** [comment]
Line 743 of amrex/Src/AmrCore/AMReX_AmrMesh.cpp is

    for (int it=0; it<4; ++it)

Try to change the number of iterations to a bigger number say 8.  If that works, we can make it a runtime parameter.

For small boxes like you have, all the data in a box can be fit into at least the L2 cache.  Moreover, the default tile size is 1024000 x 8 x 8 (where 1024000 basically no tiling in x-direction).  That is bigger than many of your boxes.  So it's not surprising there are no effects.  Also because you use AoS, maybe you can try tiling size 8 x 8 x 8.

**Comment by GumpXiaoli** [comment]
asalmgren and weiqun:

Please see the attached for my test example.

[Meshing.pptx](https://github.com/AMReX-Codes/amrex/files/2343050/Meshing.pptx)

In my example, i only use the blow loop and don't iterate the grids:
`    
  
       do

	{

	    int new_finest;

	    MakeNewGrids(finest_level,time,new_finest,new_grids);

	    if (new_finest <= finest_level) break;
	    finest_level = new_finest;

	    DistributionMapping dm(new_grids[new_finest]);

        MakeNewLevelFromScratch(new_finest, time, new_grids[finest_level], dm);

	    SetBoxArray(new_finest, new_grids[new_finest]);
	    SetDistributionMap(new_finest, dm);
	}
	while (finest_level < max_level);
`

**Comment by GumpXiaoli** [comment]
After adding iterating grids in my code, it works for the first set of parameters. But it takes longer time (50% more) to complete the mesh.

I am curious that what has been checked when iterating the grids.
