### ISSUE TITLE
on macOS, /usr/bin/gcc is actually a wrapper for clang

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#3033]
On recent versions of macOS, `/usr/bin/gcc` is actually a wrapper that just invokes Apple's build of `clang`. Usually this still manages to work, but this breaks AMReX builds with Fortran and also breaks Amrvis.

AMReX's build system should ideally detect when `gcc` is actually `clang`, and either abort or find the actual `gcc` binary. (Homebrew installs gcc as `gcc-11`, `gcc-12`, etc., so as not to interfere with Apple's fake `gcc`. On Apple Silicon, Homebrew installs itself into `/opt/homebrew`.)

**Comment by WeiqunZhang** [comment]
I don't have a Mac.  So it's hard for me to fix this.  Anyway, here is what the amrex document says
https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#gcc-on-macos.  One could also specify the compiler from command line.  `make CXX=/path/to/g++`.  Note that in the the gnu make system, we ignore the environment variables like CXX, CPPFLAGS etc. because those could also cause troubles.  In fact, it did in the past.

**Comment by BenWibking** [comment]
Ah, I missed that part of the docs. I tried to set the compiler with the CXX env var, but it wasn't working and I couldn't figure out why. That works.
