### ISSUE TITLE
Is there a way to demangle the GPU kernel names? 

### ISSUE THREAD

**Issue by PavanKumarMiriyala** [AMReX-Codes/amrex#3055]
Hello all, 

Is there any way to demangle the GPU kernel names? Currently, kernel names appear as follows:**

Example 1:
`ZN5amrex13launch_globalILi256EZNS_11ParallelForILi256EiZN12_GLOBAL__N_116ResizeRandomSeedEmEUliE_vEENSt9enable_ifIXsr19MaybeDeviceRunnableIT1_EE5valueEvE4typeERKNS_3Gpu10KernelInfoET0_OS5_EUlvE_EEvSC_.intern.d7af845c30f8642d.kd`

Example 2:
`void amrex::launch_global<256, amrex::launch<amrex::ReduceOps<amrex::ReduceOpMin, amrex::ReduceOpMax>::eval<amrex::ReduceData<double, double>, amrex::BaseFab<double>::minmax<(amrex::RunOn)0>(amrex::Box const&, int) const::{lambda(int, int, int)#1}>(amrex::Box const&, amrex::ReduceData<double, double>&, amrex::BaseFab<double>::minmax<(amrex::RunOn)0>(amrex::Box const&, int) const::{lambda(int, int, int)#1}&&)::{lambda()#1}>(int, int, unsigned long, ihipStream_t*, amrex::BaseFab<double>::minmax<(amrex::RunOn)0>(amrex::Box const&, int) const::{lambda(int, int, int)#1}&&)::{lambda()#1}>(amrex::ReduceData<double, double>&) [clone .kd]`

**Comment by WeiqunZhang** [comment]
For names like example 1, you can use `c++filt` or `cu++filt` to demangle them.  For example
```
$ c++filt _ZN5amrex13launch_globalILi256EZNS_11ParallelForILi256EiZN12_GLOBAL__N_116ResizeRandomSeedEmEUliE_vEENSt9enable_ifIXsr19MaybeDeviceRunnableIT1_EE5valueEvE4typeERKNS_3Gpu10KernelInfoET0_OS5_EUlvE_EEvSC_
void amrex::launch_global<256, amrex::ParallelFor<256, int, (anonymous namespace)::ResizeRandomSeed(unsigned long)::{lambda(int)#1}, void>(amrex::Gpu::KernelInfo const&, int
, (anonymous namespace)::ResizeRandomSeed(unsigned long)::{lambda(int)#1}&&)::{lambda()#1}>(amrex::ParallelFor<256, int, (anonymous namespace)::ResizeRandomSeed(unsigned lon
g)::{lambda(int)#1}, void>(amrex::Gpu::KernelInfo const&, int, (anonymous namespace)::ResizeRandomSeed(unsigned long)::{lambda(int)#1}&&)::{lambda()#1})
```
Unfortunately the names after being demangled still look horrible like the name in your example 2, because C++ function names with template parameters are often very long.  If you stare them long enough, you can figure out that the kernel in example 1 is in function `ResizeRandomSeed` and the second kernel is in function `BaseFab::minmax`.

If you really want to give your kernel a name, you can probably do something like this,
```
    struct WhitePaper {};
    amrex::ParallelFor(128,
    [=] AMREX_GPU_DEVICE (int i, WhitePaper = {})
    {
        // ...                                                                                                                                                           
    });
```
The kernel will still have a long name (e.g., `_ZN5amrex13launch_globalILi256EZNS_11ParallelForILi256EiZ4mainEUliZ4mainE10WhitePaperE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableIT1_vEE5valueEvE4typeERKNS_3Gpu10KernelInfoET0_OS5_EUlvE_EEvSC_`.  But it does contain the name `WhitePaper` we choose.

**Comment by PavanKumarMiriyala** [comment]
Thanks @WeiqunZhang, your suggestion is beneficial.
