### ISSUE TITLE
Interpolator to arbitrary points with multiple levels

### ISSUE THREAD

**Issue by LJPapenfort** [AMReX-Codes/amrex#306]
We doing some tests coupling our hydro toy code to AMReX using the example scalar advection code, i.e. the AmrLevel class. Everything seems to be working nicely up to now and I wanted to implement computations of some derived quantities, i.e. quantities depending on the state vector on spherical surfaces throughout the computational domain.  
We have a code to store and communicate data on a spherical grid, but I would need to couple in an iterpolator coming from AMReX which delivers the interpolated state variables on the respective sphere for the local part of the grid. Is there something like that in the framework already? Isn't this kind of interpolation also needed for the particle interface?  
In the end this will be used to do spherical surface integrals.

**Comment by drummerdoc** [comment]
The tricky part here is that you didn't say what the resulting data structure would look like.  The interpolating routines for particles either interpolated to the particle (in which case the resulting data structure is based on the particle), or to the mesh (the result is regular mesh data).  If I understand you correctly, the resulting interpolation for you will be used ultimately for integrals, but it's not clear if those integrals need ultimately to be used by the code or are just for diagnostics.  In other words, can you more clearly define exactly how the output will be used?  Can't guarantee we can help that much, but at least we'd get a better sense of where you're stuck.

**Comment by LJPapenfort** [comment]
A simple example would be the mass flux through a spheroidal surface. So yes, the results of the interpolation and integration won't be used by the code itself. It is just diagnostics.  
In the mass flux example we would be able to keep track of the flux over time and integrate it over the whole surface. From there we can get the total mass outflow. That's the most simple example which comes to my mind at the moment.  
We could do this in postprocessing, but in the future we want to compute similar integrals for which we would need high temporal accuracy. We won't be able to output the full 3D data that often for large runs.

**Comment by LJPapenfort** [comment]
To be clear: our spherical integrator would store the interpolated values in it's own memory, completely independent of AMReX.

**Comment by asalmgren** [comment]
Do you know the locations in physical space (the points on the sphere) to
which you'd like to interpolate the data?

One possibility is to place particles at those locations and allow AMReX to
ensure that the particle data is on the same rank as the grid data from
which it interpolates, then use the PIC interpolation algorithms to put the
interpolated values into the particle data.

Then you could transfer the values from the particles to your data
structure.

Would that work?

**Comment by LJPapenfort** [comment]
I had exactly the same idea. Yes, this should work. I know the points in physical space, so I would just need to know how to enable particles, how to place them on constant positions in physical space and how to call the PIC interpolation / collect the interpolated data.  
Could someone maybe point me to some example code from which I could learn the necessary steps?

**Comment by asalmgren** [comment]
Probably the easiest thing to do is to look at some of the examples in
amrex/Tutorials/Particles

For example if you look at amrex/Tutorials/Particles/NeighborList

1) In main.cpp -- this is how to declare the particle container

    NeighborListParticleContainer myPC(geom, dmap, ba, num_neighbor_cells);

    myPC.InitParticles();

and in NeighborListParticleContainer.cpp -- this is how to initialize the
particles (in this case at cell centers)

void NeighborListParticleContainer::InitParticles() {

    BL_PROFILE("NeighborListParticleContainer::InitParticles");

    const int lev = 0;
    const Geometry& geom = Geom(lev);
    const Real* dx  = geom.CellSize();

    std::mt19937 mt(0451);
    std::uniform_real_distribution<double> dist(-1.0, 1.0);

    for (MFIter mfi = MakeMFIter(lev); mfi.isValid(); ++mfi) {
        const Box& tile_box = mfi.tilebox();
        const RealBox tile_real_box { tile_box, dx, geom.ProbLo() };

        const int grid_id = mfi.index();
        const int tile_id = mfi.LocalTileIndex();
        auto& particle_tile = GetParticles(lev)[std::make_pair(grid_id,
tile_id)];

        const auto& boxlo = tile_box.smallEnd();
        ParticleType p;
        for (IntVect iv = tile_box.smallEnd(); iv <= tile_box.bigEnd();
tile_box.next(iv)) {

            p.id() = ParticleType::NextID();
            p.cpu() = ParallelDescriptor::MyProc();

            p.pos(0) = tile_real_box.lo(0) + (iv[0]- boxlo[0] + 0.5)*dx[0];
            p.pos(1) = tile_real_box.lo(1) + (iv[1]- boxlo[1] + 0.5)*dx[1];
#if (BL_SPACEDIM == 3)
            p.pos(2) = tile_real_box.lo(2) + (iv[2]- boxlo[2] + 0.5)*dx[2];
#endif
            p.rdata(0) = dist(mt);
            p.rdata(1) = dist(mt);
#if (BL_SPACEDIM == 3)
            p.rdata(2) = dist(mt);
#endif

            p.rdata(BL_SPACEDIM)   = 0;
            p.rdata(BL_SPACEDIM+1) = 0;
#if (BL_SPACEDIM == 3)
            p.rdata(BL_SPACEDIM+2) = 0;
#endif

            particle_tile.push_back(p);
        }
    }
}

2) Note that in NeighborListParticleContainer.H we declare how many
attributes the particles have:

class NeighborListParticleContainer
    : public NeighborParticleContainer<2*BL_SPACEDIM, 0>
{
says that the particles have 2*DIM attributes ... which as you see above
were initialized with dist(mt) and 0

In your case you would have only "1" instead of "2*BL_SPACEDIM" if you only
wanted to store a single value.

3) Take a look in amrex/Tutorials/Particles/ElectrostaticPIC -- subroutine
interpolate_cic interpolates from grid to particle locations.  Note that in
this case the mesh data was nodal so you'd want to change the interpolants
if you have cell-centered mesh data.

That should give you a pretty good idea -- feel free to contact me by email
(asalmgren@lbl.gov) if you get stuck
