### ISSUE TITLE
MLNodeLaplacian example

### ISSUE THREAD

**Issue by sonnendr** [AMReX-Codes/amrex#307]
I'm trying to do a simple periodic Poisson solve using MLNodeLaplacian setting sigma to 1
I was able to make it run, but it only converges with order 1 instead of the expected 2nd order.
Is there an example using such a solver and indeed showing 2nd order convergence so that I can try and figure out what I missed?

**Comment by WeiqunZhang** [comment]
Have you considered there are infinite number of solutions here because of
periodic boundaries?  If phi is a solution, phi + constant is also a
solution.

**Comment by zingale** [comment]
in general, the way to help prevent the solution from "floating" in the solver is to ensure that the discrete average of your righthand side / source term is zero.  Alternately, you can subtract the average off of the solution you get from the MG solver before doing the convergence test.

**Comment by sonnendr** [comment]
I did average the solution to 0 before comparing it to the exact solution. This is not the issue. I suspect rather an issue with the boundary conditions that are not well handled or maybe the sigma that has not been well defined, ie node centered rather that cell centred for example.
Is there no test checking that the solver has the right order of convergence?

**Comment by drummerdoc** [comment]
Yes, there is no test in the regression suite for that.

**Comment by WeiqunZhang** [comment]
Computing average and norms for nodal data is not as straightforward as cell-centered data because there are shared nodes between boxes.  One has to make sure there is no double counting.  When there are periodic boundaries, one must also make sure there is no double counting at the periodic boundaries.

Anyway, I wrote a new tutorial at `amrex/Tutorials/LinearSovlers/NodalPoisson` (currently in the development branch).  It shows perfect second-order in max and 1-norms.

**Comment by sonnendr** [comment]
Thanks for writing this new tutorial so quickly!
