### ISSUE TITLE
Ensure ProperlyNested called and FillPatcherFill documentation

### ISSUE THREAD

**Issue by philip-blakely** [AMReX-Codes/amrex#3095]
I have just spent a couple of days tracking down an "Erroneous arithmetic operation" that only triggered with CUDA and 2 levels of AMR. It turned out that the problem was with lack of proper nesting and could be easily solved by increasing amr.blocking_factor.

At present, the only calls to ProperlyNested() are in FillPatchIterator::Initialize(), AmrLevel::FillCoarsePatch(), and AmrLevel::FillPatcherFill(). Only the last of these leads to an automatic Abort. The first only displays a warning and, even then, only if amrex.verbose > 0, although it does then work out a suitable blocking_factor to help the user.

In our code, we had amrex.verbose = 0, and were using FillPatch() instead of FillPatcherFill() and so the message didn't show up.

So, could the result of a ProperlyNested() check be always to Abort, to print the useful blocking_factor suggestion, and be put somewhere that it will always be called, regardless of amrex.verbose? (Are there any cases where non-properly-nested grids are correct/useful?)

On a related note (because this could also have avoided the problem), could some guidelines on the use of FillPatch() versus FillPatcherFill() be put somewhere in the main documentation? It appears that FillPatcherFill() is now preferred since it was added last October, but there is not much documentation for it, beyond that at the top of AMReX_FillPatcher.H.

**Comment by WeiqunZhang** [comment]
The violation of proper nesting is not necessarily a fatal error in FillPatchIterator::Initialize because it has the capability of using as many coarse level as necessary to fill the fine ghost cells.  However, the code is very complicated and has not been ported GPU.   We could make that an error for GPU.  (With managed memory, I expected it would work too.  But it might have missed some synchronization.)

Re: FillPatch vs. FillPatcherFill, the latter is more error prone.  So if you are not using a Runge-Kutta scheme that requires several calls to FillPatch per step, using the old FillPatch should be just fine.  If you do use Runge-Kutta with subcycling, I would suggest using AmrLevel::RK (which will call FillPatcherFill) because filling ghost cells at coarse/fine boundary with interpolation in time is tricky.

**Comment by philip-blakely** [comment]
> But it might have missed some synchronization.

That might be the ultimate cause, then. While debugging, I set CUDA_LAUNCH_BLOCKING=1 and that solved the problem as well.
I don't have a simple reproducer, unfortunately (Tests/Amr/Advection_AmrLevel didn't trigger the problem). If I have time (rather unlikely at the moment), I might have a look through FillPatchIterator or other related code paths to see if I can narrow down the lack-of-synchronization problem.

> So if you are not using a Runge-Kutta scheme that requires several calls to FillPatch per step, using the old FillPatch should be just fine.

Thank you; we'll stick to FillPatch for the moment, then.

Your latest PR #3098 is fine for us as a solution to this issue.
