### ISSUE TITLE
AMReX-based Profiler using float

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#312]
Is there anyone has experience using AMReX-base profiler using float precision. It seems that there is a bug for profiler in such case. 
![screenshot from 2018-09-12 09-13-17](https://user-images.githubusercontent.com/30617135/45396214-bd182700-b66c-11e8-94ef-c0d0dc182523.png)

**Comment by WeiqunZhang** [comment]
I think the way to fix this is to use `double` explicitly instead of `Real` in `BLProfiler` and use `amrex::second` rather than `ParallelDescriptor::second`.   The reason for using `double` is obvious.  As for the two `second` functions, the difference is `amrex:second` returns the time since the beginning of the run whereas `ParallelDescriptor::second` returns the time since an arbitrary time in the past.  On my machine, `amrex::second` returns a `double` like `0.04139...`, whereas `ParallelDescriptor::second` returns a `double` like `1536726418.68...`.  Since float has only about 7 decimal digits, it's not surprising the difference of two floats (converted from doubles returned by `ParallelDescriptor::second`) becomes negative.  There is another reason for preferring `amrex::second`.  I did some tests on NERSC before and found that the precision of `MPI_Wtime` was 1.e-6 second (using `MPI_Wtick`) whereas C++ timer had 1.e-9 second precision.  (This was the reason TINY_PROFILE uses `amrex::second`.)

**Comment by WeiqunZhang** [comment]
I switched the timer in the full profiler from `MPI_Wtime` to C++ clock in the development branch.   It should work for float now.  Using `double` everywhere in `BLProfiler` won't be easy because it writes the data as `amrex::Real` in plotfiles.  So we probably won't do anything to it.

**Comment by GumpXiaoli** [comment]
Many Thanks! Weiqun. 
By the way, i just wonder Visit can view the profiler file? I always use Visit to plot the results.

**Comment by WeiqunZhang** [comment]
I think you have to use Amrvis for profiler plotfiles.
