### ISSUE TITLE
Difference between AdvectWithUmac and AdvectWithUcc in TracerParticleContainer

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#338]
I can understand the meaning of AdvectWithUcc, but confused about the AdvectWithUmac. Can anyone help explain?

**Comment by atmyers** [comment]
The difference is that AdvectWithUcc is for cell-centered velocity fields, while AdvectWithUmac is for staggered velocity fields, where the x-velocity lives on the x faces, the y-velocity on the y-faces, etc. This makes the indexing in the mesh-to-particle interpolation slightly different, but otherwise they are the same.
