### ISSUE TITLE
Difference of BoxList, BoxDomain and BoxArray

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#353]
I have used AMReX for some time. I am now confused about the difference of three classes: BoxList, BoxDomain and BoxArray. 

What i care about mostly is : 
Can boxes in BoxArray overlap each other?

**Comment by drummerdoc** [comment]
In a word, yes.  In practice, you can think of BoxArray typically as a semi-permanent kind of structure.  We use them to define MultiFab's for example, or to define an AmrLevel, and often associate distribution mappings with them.  BoxDomains and BoxLists are usually more of a temporary used to compute things like intersections and overlaps.  BoxDomains are typically disjoint, BoxLists are just plain old lists of Boxes.  This, of course, if all subject to programming styles, but that's kind of the general rules of thumb.  Hope that helps.

**Comment by drummerdoc** [comment]
Sorry, not to go on and on, but I'll go on and on...  Generally, Array objects (or, Vectors) are infrequently resized because there is an assumption that the elements of the array are contiguous in memory.  Lists are typically implemented in some kind of linked fashion that allows for efficient resizing and mid-insertions.  BoxArray and BoxList classes were developed with that semantic implied, and so their usage in code is typically, but not necessarily, distinct. BoxDomain was created to help with Box calculus operations, etc.  It is largely superfluous, and mainly retained for backward compatibility.

**Comment by GumpXiaoli** [comment]
If there are boxes overlapping each other in one single multifab, can i call FillBoundary function?

**Comment by drummerdoc** [comment]
FillBoundary (by default anyway) only copies data from valid to grow regions.  If the data is ambiguously defined for a given index, the resulting grow cell there will have *one* of the valid values, but it is not well-defined which of the ambiguous values it will be.  It is up to the user to ensure that ambiguously defined values are treated as expected.  

For example, if you have face-centered data, the data in adjacent boxes that live on the same face index will be multiply/ambiguously defined.  This can be used to your advantage.  For example, you may wish to increment to a result, rather than copy.  That is supported, in some of the AMReX functionality.  But, you do have to be careful to properly manage that situation if you, as an app developer, wants to allow that to happen.

**Comment by GumpXiaoli** [comment]
I am trying to write my own version of FillPatchTwoLevels function. When studying the original version, i think fpc.ba_crse_patch is one boxarray in which boxes will overlap each other. Is that right?

**Comment by WeiqunZhang** [comment]
yes
