### ISSUE TITLE
Bug in FillPatchSingleLevel function

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#354]
I think there is a bug in the last line of FillPatchSingleLevel function.

![1](https://user-images.githubusercontent.com/30617135/47555820-65ddc580-d93f-11e8-9ad2-44a38a869156.PNG)

physbcf.FillBoundary is used for filling the physical domain boundary ghost cells with components starting from dcomp to dcomp+ncomp-1.

However, when checking the implementation of this function in the file AMReX_PhysBCFunct.cpp, i found that only physical boudnary ghost cells of the first component is filled.

![2](https://user-images.githubusercontent.com/30617135/47556243-6a56ae00-d940-11e8-88b5-7321f12b5741.PNG)

**Comment by ajnonaka** [comment]
By my understanding, the instance of FillBoundary in AMReX_PhysBCFunct.cpp is only meant to be an example.  If you look at the comment in AMReX_PhysBCFunc.H

`    // note this is pure virtual and must be implemented in a derived class
    // (see PhysBCFunct below for an example)
    virtual void FillBoundary (MultiFab& mf, int dcomp, int ncomp, Real time) = 0;
`
Does anybody have any opinions about whether the provided example should implement dcomp and ncomp?

**Comment by GumpXiaoli** [comment]
In the tutorial example "Advection_AmrCore", the fillpatch member function just uses built-in PhysBCFunct as input, which may cause some problems.

**Comment by ajnonaka** [comment]
Advection_AmrCore only has 1 component, so I think it's ok.  Perhaps the best solution is to put an Abort() in PhysBCFunct::FillBoundary if dcomp != 0 or ncomp != 1 to prevent problems, and indicate that a custom routine is needed.

**Comment by WeiqunZhang** [comment]
My opinion is no change is need.

For one to use `PhysBCFunct`, the user must provide its own `BndryFunctBase`.  So the user can easily use it to fill arbitrary `dcomp` and `ncomp`.   Maybe they always have `dcomp = 0` and `ncomp = 10`.  Maybe they save them somewhere that the function in `BndryFunctBase` has access to.  Adding assertion may break some codes in order to fix a non-bug (because we clearly say you could/should write your own class).

I think Linus Torvalds would agree with me.  He likes to say "do not break userspace".

**Comment by GumpXiaoli** [comment]
I think users should have their own `BndryFuncBase` and `PhysBCFunct`. Otherwise, the built-in `FillPatchSingleLevel` will have problems.

**Comment by WeiqunZhang** [comment]
That's why FillPatchSingleLevel takes polymorphic type.
