### ISSUE TITLE
Profiling .f, .F, and .F90 files

### ISSUE THREAD

**Issue by spatel7286** [AMReX-Codes/amrex#355]
I am interested in profiling one of the subroutines in the fortran source code.  For example, my case is using the IAMR code and it calls the amrex_abec_gsrb subroutine in AMReX_ABec_3D.F90.  

I have tried to instrument per the documentation by writing

call bl_proffortfuncstart("abec")
...
call bl_proffortfuncstop("abec")

However, this has not displayed any timing information in the STDOUT when using TINY_PROFILER.  Am I missing something?  the profiling instrumentation seems to work for .cpp files however I am not sure how to use the BL_Profiler functions for Fortran files.  

Any help would be much appreciated. 

Best,

-ssp

**Comment by kngott** [comment]
Unfortunately, the Fortran profiling is currently unavailable in the TinyProfiler. The TinyProfiler is meant as a simple, overall tool to get general information about an application. The full profiler is required to properly handle the fortran timers, data storage and analytics.

However, the full profiler has a STDOUT text based output similar to the TinyProfiler, so if you're interested in obtaining fortran timers, just use PROFILE=TRUE instead of TINY_PROFILE=TRUE. You can then, either browse the rest of the profiling documentation and explore the additional infomration in the generated profiling database "blprof", or just delete it at your leisure and use the basic STDOUT information.

Speaking of the documentation, I'm also making some adjustments to the profiler docs that will hopefully clear up the confusion. These changes should be up shortly.

If you need any other help or have any other questions, please let us know.
