### ISSUE TITLE
Invalid Particle Treatment

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#383]
When I forcely set one particle to invalid state, i have two methods:
1) set the id to -1
2) set the position out of the physical domain, and call redistribute.

Can both work? Now i use the second one.

**Comment by atmyers** [comment]
You can set the id to -1 and then call Redistribute, and the particle will be removed. Setting it outside the physical domain will only work if you use non-periodic boundary conditions - otherwise it will be shifted inside. If you want to ignore the particle in any user code in between setting its id to -1 and calling Redistribute, you'll need to do that manually.

**Comment by atmyers** [comment]
The particle will be removed from the associated vector and its destructor will be called, but the memory won't necessarily be freed.
