### ISSUE TITLE
ParticleContainer Copy

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#387]
I have two ParticleContainer with different boxarray. How can i copy one to another?

**Comment by GumpXiaoli** [comment]
How to deal with this case:

in A, one processor has non-empty m_particles
in B, the same processor only has a empty m_particle. (this means there is no box in this processor)

**Comment by atmyers** [comment]
You don't have to add the particles to the correct box in B. If you put them in the wrong place - say, you create an entry in m_particles corresponding to the box that exists in A but not in B for the processor in question - the next call to Redistribute() will fix it.

**Comment by atmyers** [comment]
Because m_particles[lev] is a std::map, the [] operator will create a new entry for the box if one doesn't exist already. That entry will be removed on the next Redistribute call if no particles really belong there based on the BoxArrays / DistributionMappings for each level. 

I just added two new methods to ParticleContainer - one that clears all the particles in the container, and another that copies particles from another container. These are in the latest development version of AMReX. Let me know if those work for you. If the copyParticles one doesn't do exactly what you want, you might be able to modify it yourself in your application.

**Comment by GumpXiaoli** [comment]
I got it. Thank you very much!
