### ISSUE TITLE
Usage of FillPatch and FillBoundary

### ISSUE THREAD

**Issue by aerojpapp** [AMReX-Codes/amrex#391]
Hello All,

Looking through the example problems it isn't self evident when/if to use FillBoundary and when to use FillPatch?  Does FillPatch supersede FillBoundary when using multiple refinement levels or can FillPatch be used for any problem regardless of whether there are multiple mesh levels?  If so, why does the heat equation example use FillBoundary but the advection one doesn't?  What if I don't want to use any temporal interpolation.  What if all I want to do is project the coarse results to the fine grid's ghost cells.  Is there a way to do that using FillPatch?

Thanks,

John

**Comment by ajnonaka** [comment]
> Looking through the example problems it isn't self evident when/if to use FillBoundary and when to use FillPatch? 

FillBoundary is a single-level operation only that fills ghost cells from neighboring interior grids as well as periodic boundaries.  FillPatch is a more general routine that says "fill up this MultiFab's data, including ghost cells, by copying in data from existing regions, and interpolating in space and/or time from coarse and/or fine levels if the data in that region did not previously exist"

> Does FillPatch supersede FillBoundary when using multiple refinement levels or can FillPatch be used for any problem regardless of whether there are multiple mesh levels?

You can always write code using only FillPatch routines and not ever directly calling FillBoundary.  So FillPatch can supersede FillBoundry for both single and multi-level problems.  Look at `amrex/Src/AmrCore/AMReX_FillPatchUtil.H`.  There are functions called `FillPatchSingleLevel` and `FillPatchTwoLevels`.  `FillPatchSingleLevel` can interpolate in time.  `FillPatchTwoLevels` can interpolate in space and time.  But you can rig up `FillPatchTwoLevels` to interpolate only in space (see below).

> If so, why does the heat equation example use FillBoundary but the advection one doesn't?

The heat equation example is single-level.  It could have been written to use `FillPatchSingleLevel` instead of `FillBoundary`.

> What if I don't want to use any temporal interpolation. What if all I want to do is project the coarse results to the fine grid's ghost cells. Is there a way to do that using FillPatch?

What I have done is use FillPatchTwoLevels, and make sure the input coarse time and fine time match the time I want the data at.  And then the input coarse and fine MultiFabs are vectors containing only 1 MultiFab each. So it will do purely spatial interpolation.

**Comment by ruihai0925** [comment]
Hi Andy,

Another confusing after John's question. Suppose we already have the interior cell values of a multitab, Fillpatch will only interpolate the ghost cell values and keep the original interior cell value (no matter what kinds of interpolation scheme we use). Is it correct?

Thanks.

Jordan

**Comment by ajnonaka** [comment]
Yes, as long as your're not interpolating in time.

Look at `amrex/Src/AmrCore/AMReX_FillPatchUtil.cpp` function `FillPatchTwoLevels`:

```
void FillPatchTwoLevels (MultiFab& mf, Real time,
 		         const Vector<MultiFab*>& cmf, const Vector<Real>& ct,
		         const Vector<MultiFab*>& fmf, const Vector<Real>& ft, ...
```

The output `mf` is associated with the fine level.  The inputs `cmf` and `fmf` are (possibly multicomponent vectors) associated with different times `ct` and `ft`.  So if you choose a `time` that exactly matches an entry in `ft`, any data in `fmf` corresponding to a valid region in `mf` will simply be copied into `mf`.

**Comment by aerojpapp** [comment]
That did the trick.

Thanks,

John
