### ISSUE TITLE
what is the definition of "finest_level" in AMRCore 

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3923]
I just find "finest_level" is not equal to the "max_level + 1" in the code, I want to know what is the definition of the finest_level.

**Comment by WeiqunZhang** [comment]
Both `finest_level` and `max_level` start with 0. So `finest_level == max_level + 1` can never be true because of `+1`. But that might not be why you asked the question.  Is the question about the difference between `finest_level` and `max_level`? `finest_level` is the current finest level, whereas `max_level` is the maximum that the finest level can possibly be.

**Comment by ztdepztdep** [comment]
Thanks. I want to know which part of the code update the value of "finest_level" in the AMRcorel.

**Comment by WeiqunZhang** [comment]
In `regrid`
