### ISSUE TITLE
MHD Interpolator in FillPatchUtil.cpp/InterpCrseFineBndryEMfield( ) function

### ISSUE THREAD

**Issue by iyildiran** [AMReX-Codes/amrex#397]
Dear all;

I am currently using an incompressible flow solver with fully-staggered grid arrangement and I want to couple it with Amrex. For prolongation from coarse to a fine level, I want to employ a divergence-free interpolator for face-centered data. I intended to use Balsara's scheme for MHD problem (JCP,2002). Later I figured out that it is already implemented in InterpCrseFineBndryEMfield() function contained in FillPatchUtil.cpp/H.

- But honestly, I don't know how I should use that MHD interpolator in my simulation. I keep each velocity components (u,v,w) in different MultiFabs with different StateTypes. Where and how should I call that function? How am I going to provide input parameters while it is within FillPatch routines?
- The second question is, within the InterpCrseFineBndryEMfield() function there is a FabArrayBase::TheCFinfo(const FabArrayBase& finefa,...) function and I totally did not understand what it's doing. Can you describe its purpose?

I very much appreciate your help.
Kind regards,
Ibrahim

**Comment by iyildiran** [comment]
Dear Weiqun,

Thank you so much for your reply. I can still use the current implementation of that interpolator right? As you said, the interpolator fills the fine ghost cells, and I think I am going to call FillPatchSingleLevel to fill the valid data afterward. So what I actually do is manipulating the FillPatchTwoLevels function, don't I?

Do you agree on these? If not, can you suggest a way to incorporate that interpolator in my incompressible flow simulation? You said part of the paper was implemented, then should I update the fortran function of the interpolator?

Thank you,
Ibrahim

**Comment by drummerdoc** [comment]
``
I keep each velocity components (u,v,w) in different MultiFabs with different StateTypes.
``
I get why you do this, but it seems like we should think about whether this is a sufficiently useful setup that warrants some special support at the library level.

**Comment by drummerdoc** [comment]
... in particular, this looks a lot like why why have a bunch of special code in `IAMR` for `fill_umac_grown`

**Comment by iyildiran** [comment]
Thank you Marc,

> I get why you do this, but it seems like we should think about whether this is a sufficiently useful setup that warrants some special support at the library level.

Yes I definitely agree, but I couldn't find any other way yet. In IndexType class, there are only CELL and NODE options. I created TheNodeTypeX, TheNodeTypeY and TheNodeTypeZ within the class to represent face-centeredness while I was adding them to DescriptorList. Probably the major drawback is that I cannot use any interpolators, therefore I am looking for a way to incorporate Balsara's scheme contained in InterpCrseFineBndryEMfield function. For restriction process, there is an option average_down_face. Hence, it is not that intricate. Can you suggest any other way to deal wtih fully-staggered arrangement and/or interpolator?

> ... in particular, this looks a lot like why why have a bunch of special code in `IAMR` for `fill_umac_grown`

Since IAMR stores the velocities at centers and pressure at nodes, I couldn't make use of that code efficiently. By the way, where is this fill_umac_grown?

Kind regards,
Ibrahim

**Comment by WeiqunZhang** [comment]
The difference between `fill_umac_grown` and `InterpCrseFineBndryEMfield` is the first one does not create divergence free field, whereas the second satisfies div B = 0.  So it depends what the algorithm wants.  Most MHD codes don't do any kind of projections.

Again `InterpCrseFineBndryEMfield` only works for **fixed** meshes, it doesn't work for **adaptive** mesh refinement.  Adaptive mesh might be supported in the future and one might be able to just call FillPatch.

**Comment by iyildiran** [comment]
> The difference between `fill_umac_grown` and `InterpCrseFineBndryEMfield` is the first one does not create divergence free field, whereas the second satisfies div B = 0. So it depends what the algorithm wants. Most MHD codes don't do any kind of projections.

I need divergence-free field due to div u = 0.
 
> Again `InterpCrseFineBndryEMfield` only works for **fixed** meshes, it doesn't work for **adaptive** mesh refinement. Adaptive mesh might be supported in the future and one might be able to just call FillPatch.

Ok I understand. I think I should somehow add an interpolator for face centered variables to Interpolator.cpp/H and use FillPatch routines directly.

**Comment by drummerdoc** [comment]
As I said, I understand the issues associated with divergence-free interpolation, and that there is currently no library support for that data type.

In `IAMR` the mac velocities are derived during the time step operations and live on cell faces.  They are defined by a projection operation in such a way that they are not determined in the grow cells beyond coarse-fine boundaries.  Since the advection discretization needs velocities in that region, we must define an interpolation/extrapolation scheme for them.  Ideally, this would satisfy the (possibly inhomogeneous) divergence constraint, as represented on the coarse level - when it is used as part of the `PeleLM` time advance, Div(U) is specified function of the state and is non-zero over some the domain.  At the moment, we have a simple interpolating scheme that is "good enough", but the approach can almost certainly be improved using the ideas from the MHD work where one has a stronger motivation to preserve the divergence condition.  

If a suitably contained solution to this could be developed that incorporated an effective interpolation scheme with nice properties, there are other applications that could benefit, such as `IAMR`.  I am not suggesting I know how to do this, but rather to think of the solution eventually settled upon as potentially useful for others and thus worth incorporating into the library.  More generally, to acknowledge that staggered-grid solutions are used across many applications, and yet are not easily supported in the current Amr infrastructure within AMReX.  Thus, when a strategy is functioning, it would be nice to learn about it and explore whether it's worth importing for others to use.

**Comment by iyildiran** [comment]
Thank you, Marc and Weiqun for your valuable recommendations. I will consider them and try to come up with a functioning algorithm.

Ibrahim
