### ISSUE TITLE
ParmParse prefix interface

### ISSUE THREAD

**Issue by bsrunnels** [AMReX-Codes/amrex#4084]
Some of the `ParmParse` prefix-related tools have disappeared in 24.08, namely
* `getPrefix()`
* `setPrefix()`
* `pushPrefix()`
* `popPrefix()`

Alamo depends on those for its workflow. Is there an updated interface to the prefix list that we can use, or if not, is it possible to add back the original one? thanks!

**Comment by WeiqunZhang** [comment]
I looked at how Alamo uses these functions, I think it's better to avoid `push` and `pop`, because one has to remember to `pop`. I think we can add back `setPrefix` and `getPrefix`. Then you can do something like,
```
ParmParse pp = *this;
auto prefix = getPrefix();
if (prefix.empty()) {
    pp.setPrefix(name);
} else {
    pp.setPrefix(prefix+"."+name);
}
T::Parse(value, pp);
if (amrex::ParmParse::hasUnusedInputs(pp.getPrefix()) { ... }
```

You can also fix it by not requiring any changes in amrex.
```
auto old_prefix = m_prefix;
if (old_prefix.empty()) {
    m_prefix = name;
} else {
    m_prefix.append(".").append(name);
}
T::Parse(value, *this);
if (amrex::ParmParse::hasUnusedInputs(m_prefix)) { ... }
m_prefix = std::move(old_prefix);
```

Let me know what you think.

**Comment by bsrunnels** [comment]
@WeiqunZhang That sounds good, thanks for the quick response. 

I implemented the fix you suggested and it works fine. Thanks!
