### ISSUE TITLE
Re: Multifab to hold derived data types

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/amrex#414]
Hi,

We are developing a solver for which we need to have custom data types to be held by the multifab. For example, we want to do

type(planarlocalizer_type), contiguous, pointer, dimension(:,:,:) :: plocalizer
plocalizer => phi_new(lev)%localizer

and then use things like plocalizer(i,j,k)%stuff1, plocalizer(i,j,k)%stuff2 etc.

I was told in a reply to an earlier post on this issue that planarlocalizer_type should be bind(c). But I should mention that it has type bound procedures (stuff1, stuff2) within it. So the compiler does not allow it to be bind(c). Any workarounds? Thanks for your help.

**Comment by WeiqunZhang** [comment]
You probably should avoid type-bound procedures.  I don't think there are any workarounds.  My understanding is type-bound procedures with `class` dummy argument are like C++ virtual functions.  So the derived type has to store runtime type information in order to be able to do dynamic dispatch at runtime.

The good thing is avoiding type-bound procedures will probably make your code faster.

**Comment by nataraj2** [comment]
Alright. So no need to spend time looking for workarounds for this. Will look into avoiding type-bound procedures. Thanks, Weiqun.
