### ISSUE TITLE
the intent of usePrePost in ParticleContainer

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#453]
I can hardly understand the meaning of the member "usePrePost" in ParticleContainer. May someone help me figure it out?

**Comment by atmyers** [comment]
`usePrePost` is an IO optimization that reduces the number of synchronization points when writing the particle plotifles and checkpoints. When that option is on, instead of having parallel reductions and barriers dispersed within the main Checkpoint routine, they are all done either at the beginning or the end. This can improve the overall IO performance on large jobs.

**Comment by GumpXiaoli** [comment]
Understood! Thanks for your explanation.
