### ISSUE TITLE
convert method on amrex_boxarray (fortran)

### ISSUE THREAD

**Issue by pbrady** [AMReX-Codes/amrex#49]
The convert method on an amrex_boxarray does not appear to be exposed via the fortran interface.  Is there a straight-forward way to duplicate (via fortran) the functionality of the c++ code on page 26 of the amrex docs?

```c++
// ba is cell - centered BoxArray
// dm is DistributionMapping
int ncomp = 3; // Suppose the system has 3 components
int ngrow = 0; // no ghost cells
MultiFab state ( ba , dm , ncomp , ngrow );
MultiFab xflux ( amrex :: convert ( ba , IntVect {1 ,0 ,0}) , dm , ncomp , 0);
MultiFab yflux ( amrex :: convert ( ba , IntVect {0 ,1 ,0}) , dm , ncomp , 0);
MultiFab zflux ( amrex :: convert ( ba , IntVect {0 ,0 ,1}) , dm , ncomp , 0);
```

**Comment by WeiqunZhang** [comment]
Yes, you are right.  The `convert` method for `BoxArray` is not exposed in the Fortran interface.   There are some subtleties due to the difference between Fortran and C++.   

But for the example you show, we do not need the `convert` method.  One can do

    call amrex_multifab_build(xflux, ba, dm, ncomp, ngrow, (/ .true. , .false., .false. /))
    call amrex_multifab_build(yflux, ba, dm, ncomp, ngrow, (/ .false., .true. , .false. /))
    call amrex_multifab_build(zflux, ba, dm, ncomp, ngrow, (/ .false., .false., .true.  /))

If you really need the `convert` method, please let us know.

**Comment by pbrady** [comment]
@WeiqunZhang, That exactly what I wanted.  I don't think I'll need access to the `convert` method.  Thanks.
