### ISSUE TITLE
Problems with BoxLib Plugin for VisIt 

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#542]
Dear AMReX community, 

if I am completely wrong here, I will raise this issue in VisIts repository, too. I was under the impression that someone here has written or adjusted the BoxLib plugin to open AMReX plot files.

Sometimes the BoxLib plugin in VisIt fails to open data written by `amrex::WritePlotData()` and I do not know why. Have anyone made a similar experience? 

This plot file [00784.zip](https://github.com/AMReX-Codes/amrex/files/3477079/00784.zip) does not open in VisIt and the error message is:
```
Running: viewer3.0.0 -debug 5 -geometry 990x960+690+3 -borders 20,0,0,1 -shift 0,0 -preshift 0,0 -defer -host 127.0.0.1 -port 5600
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5604
BoxLib::Error::Read of Array<Array<Real>> failed !!!
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5604
BoxLib::Error::Read of Array<Array<Real>> failed !!!
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5604
BoxLib::Error::Read of Array<Array<Real>> failed !!!
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5600
BoxLib::Error::Read of Array<Array<Real>> failed !!!
```

But this plot file [00840.zip](https://github.com/AMReX-Codes/amrex/files/3477089/00840.zip) does open, some time steps later.

VisIt also fails to show the correct cycle information and prints some seamingly overflowed or uninitialized value as cycle number.

Any Ideas? Thank you,
Maikel

**Comment by asalmgren** [comment]
Which version of visit are you using?

Sent from my iPhone

On Aug 7, 2019, at 8:01 AM, Maikel Nadolski <notifications@github.com>
wrote:

Dear AMReX community,

if I am completely wrong here, I will raise this issue in VisIts
repository, too. I was under the impression that someone here has written
or adjusted the BoxLib plugin to open AMReX plot files.

Sometimes the BoxLib plugin in VisIt fails to open data written by
amrex::WritePlotData() and I do not know why. Have anyone made a similar
experience?

This plot file 00784.zip
<https://github.com/AMReX-Codes/amrex/files/3477079/00784.zip> does not
open in VisIt and the error message is:

Running: viewer3.0.0 -debug 5 -geometry 990x960+690+3 -borders
20,0,0,1 -shift 0,0 -preshift 0,0 -defer -host 127.0.0.1 -port 5600
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5604
BoxLib::Error::Read of Array<Array<Real>> failed !!!
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5604
BoxLib::Error::Read of Array<Array<Real>> failed !!!
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5604
BoxLib::Error::Read of Array<Array<Real>> failed !!!
Running: mdserver3.0.0 -debug 5 -host 127.0.0.1 -port 5600
BoxLib::Error::Read of Array<Array<Real>> failed !!!

But this plot file 00840.zip
<https://github.com/AMReX-Codes/amrex/files/3477089/00840.zip> does open,
some time steps later.

VisIt also fails to show the correct cycle information and prints some
seamingly overflowed or uninitialized value as cycle number.

Any Ideas? Thank you,
Maikel

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AMReX-Codes/amrex/issues/542?email_source=notifications&email_token=ACRE6YQGLDFMEIO3SZO77YTQDLBQ5A5CNFSM4IKAEGV2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HD4M3YQ>,
or mute the thread

**Comment by maikel** [comment]
I tested that for VisIt 3.0 and VisIt 2.13 with the binaries available at https://wci.llnl.gov/simulation/computer-codes/visit/executables

**Comment by asalmgren** [comment]
In the ascii files in each level directory we print the min and max of each
field.  Can you verify those numbers are what you expect (and not NaN for
example)?

Sent from my iPhone

On Aug 7, 2019, at 8:48 AM, Maikel Nadolski <notifications@github.com>
wrote:

I tested that for VisIt 3.0 and VisIt 2.13 with the binaries available at
https://wci.llnl.gov/simulation/computer-codes/visit/executables

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/AMReX-Codes/amrex/issues/542?email_source=notifications&email_token=ACRE6YTPAVVTEI2QQQS3KSTQDLHDXA5CNFSM4IKAEGV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3YOWBY#issuecomment-519105287>,
or mute the thread

**Comment by maikel** [comment]
AFAIK it seems ok. The plotfile with only one refinement level which does not work seems to not contain any NaN's in any of the Header files, the maxima seem to be ok. As for the content of the binary data, I have not checked yet.

I wrote the data calling `amrex::EB_WriteMultiLevelPlotfile` and not `amrex::WritePlotData` as I stated before. (sorry)

The content of "00784/Header":

```
HyperCLaw-V1.1
21
Density
Momentum_0
Momentum_1
Energy
N2
AR
H
O2
O
OH
H2
H2O
HE
HO2
H2O2
Pressure
SpeedOfSound
Temperature
HeatCapacityAtConstantPressure
HeatCapacityRatio
vfrac
2
0.00028333333333333341
0
-0.10000000000000001 -0.14999999999999999 
0.20000000000000001 0.14999999999999999 

((0,0) (255,255) (0,0)) 
784 
0.0011718750000000002 0.001171875 
0
0
0 4 0.00028333333333333341
784
-0.10000000000000001 0.050000000000000017
-0.14999999999999999 0
0.050000000000000017 0.20000000000000004
-0.14999999999999999 0
-0.10000000000000001 0.050000000000000017
0 0.14999999999999999
0.050000000000000017 0.20000000000000004
0 0.14999999999999999
Level_0/Cell
1.0e-6
```

The content of "00784/Level_0/Cell_H"

```
1
1
21
0
(4 0
((0,0) (127,127) (0,0))
((128,0) (255,127) (0,0))
((0,128) (127,255) (0,0))
((128,128) (255,255) (0,0))
)
4
FabOnDisk: Cell_D_00001 0
FabOnDisk: Cell_D_00001 2752597
FabOnDisk: Cell_D_00000 0
FabOnDisk: Cell_D_00000 2752599

4,21
0.0000000000000000e+00,-1.0302470832770652e-14,0.0000000000000000e+00,-9.9097555216980603e+04,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,
1.1721800213734208e+00,0.0000000000000000e+00,0.0000000000000000e+00,-9.9097555216980603e+04,8.9920024803047471e-01,0.0000000000000000e+00,0.0000000000000000e+00,2.7297977334294626e-01,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,1.0132499999999999e+05,3.4780828987399775e+02,3.0000000000000000e+02,1.0094749992461950e+03,1.3994505612501784e+00,1.0000000000000000e+00,
0.0000000000000000e+00,-1.0302470832770652e-14,-5.8199712332853014e-14,-9.9097555216980603e+04,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,
1.1721800213734208e+00,0.0000000000000000e+00,-1.8618637622766290e-27,-9.9097555216980603e+04,8.9920024803047471e-01,0.0000000000000000e+00,0.0000000000000000e+00,2.7297977334294626e-01,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,1.0132499999999999e+05,3.4780828987399775e+02,3.0000000000000000e+02,1.0094749992461950e+03,1.3994505612501784e+00,1.0000000000000000e+00,

4,21
1.1721800213734208e+00,5.7641375637036577e-14,5.8199712332853014e-14,0.0000000000000000e+00,8.9920024803047471e-01,0.0000000000000000e+00,2.8909029543103225e-138,2.7297977334294626e-01,3.2577984069286225e-80,8.8852001232986879e-143,2.5195618601906425e-99,4.5796157324547840e-146,0.0000000000000000e+00,2.0525107371726194e-133,1.3962927112766456e-141,1.0132499999999999e+05,3.4780828987399775e+02,3.0000000000000000e+02,1.0094749992461950e+03,1.3994505612501784e+00,1.0000000000000000e+00,
1.1721800213734208e+00,0.0000000000000000e+00,1.8618637622766355e-27,-9.9097555216980603e+04,8.9920024803047471e-01,0.0000000000000000e+00,8.7107828442732136e-305,2.7297977334294626e-01,2.9114012629602995e-154,1.7963714588177977e-309,7.5918688983005789e-266,3.8289858302778477e-313,0.0000000000000000e+00,4.1482099279105936e-300,3.2147736414981928e-308,1.0132499999999999e+05,3.4780828987399775e+02,3.0000000000000000e+02,1.0094749992461950e+03,1.3994505612501784e+00,1.0000000000000000e+00,
1.1721800213734208e+00,5.7641375637031743e-14,0.0000000000000000e+00,0.0000000000000000e+00,8.9920024803047471e-01,0.0000000000000000e+00,2.8909029543103225e-138,2.7297977334294626e-01,3.2577984069286225e-80,8.8852001232986879e-143,2.5195618601906425e-99,4.5796157324547840e-146,0.0000000000000000e+00,2.0525107371726194e-133,1.3962927112766456e-141,1.0132499999999999e+05,3.4780828987399775e+02,3.0000000000000000e+02,1.0094749992461950e+03,1.3994505612501784e+00,1.0000000000000000e+00,
1.1721800213734208e+00,0.0000000000000000e+00,0.0000000000000000e+00,-9.9097555216980603e+04,8.9920024803047471e-01,0.0000000000000000e+00,8.7107828442732136e-305,2.7297977334294626e-01,2.9114012629602995e-154,1.7963714588177977e-309,7.5918688983005789e-266,3.8289858302778477e-313,0.0000000000000000e+00,4.1482099279105936e-300,3.2147736414981928e-308,1.0132499999999999e+05,3.4780828987399775e+02,3.0000000000000000e+02,1.0094749992461950e+03,1.3994505612501784e+00,1.0000000000000000e+00,
```

**Comment by ajnonaka** [comment]
I am able to open plotfile 00784 with VisIt 2.13.1 on my laptop.

**Comment by maikel** [comment]
Indeed, I can open the file with Linux but not with the MacOs binaries of VisIt. I will close this issue for now.

**Comment by maikel** [comment]
I reopen this issue on GitHub because the Cycle Information is still wrongly displayed even on Linux.

**Comment by asalmgren** [comment]
Through experimentation we have discovered the problem:

Apparently the Visit reader determines "Cycle" not by reading the Header
file but from the name of the plotfile (directory)

And ... the way it figures out what the number is from that name is by
taking the digits after the string "plt"

So ... if you call it myplt00100 or this_is_my_plt00100 then it will
correctly recognize and print Cycle: 100

But if you call it simply 00100 or even pltt00100 then it will not grab the
correct number.

My guess is that fixing this would be a relatively low priority for the
Visit team so my suggestion is just to make sure your plotfiles end with
"...pltXXXXX"

**Comment by maikel** [comment]
Renaming the plot files worked for me! Thank you!
