### ISSUE TITLE
Internals of MLNodeLaplacian

### ISSUE THREAD

**Issue by svater** [AMReX-Codes/amrex#570]
Hi,

I am trying to understand the internals of MLNodeLaplacian, because I would like to implement a nodal varable coefficient Poisson solver with different stencils. However, I like the multilevel multigrid solution strategy you are using in amrex for this. In followup of #342, is there any more documentation about this method apart from 

[https://ccse.lbl.gov/Publications/almgren/abchw.pdf](https://ccse.lbl.gov/Publications/almgren/abchw.pdf)?

Also in terms of code documentation, such as doxgen?

Is there any documentation with respect to embedded boundaries, although this is only a task for the future? I have also some special questions about embedded boundaries: Am I correct that this mode is marked by setting 

`m_coarsening_strategy = CoarseningStrategy::RAP` ?

Then it seems that the `buildStencil()` function is only for this case, and I can ignore it, until I deal with embedded boundaries?

I hope my questions are not too trivial and you can aswer them.

Thanks a lot,
Stefan

**Comment by asalmgren** [comment]
Stefan --

1) Are you interested in the details of how we construct the stencil, or
the details of how the solver is implemented?  For the former I can happily
send you a pdf of the gory detail of computing the integrals that define
the stencil (it is based on a finite element representation in which we
compute integrals on each cell to determine coefficients for the nodal
stencil).  For the latter we don't have better documentation at this point
but I can point you to Brandon Runnels who recently modified the nodal
stencil for his application and might be able to tell you exactly where the
modifications needed to be made.

2) m_coarsening_strategy defines how the operator should be coarsened -- it
does not by itself control the use of embedded boundaries.  To use the
stencils that see the cut cells you need to build with USE_EB = TRUE and
build your MulitFabs to be eb-aware (i.e build them with the ebfactor
information).  It is the case that if USE_EB = true then we use the RAP
rather than Sigma coarsening -- see hte following in AMReX_MLNodeLaplacian.H

#ifdef AMREX_USE_EB
    CoarseningStrategy m_coarsening_strategy = CoarseningStrategy::RAP;
#else
    CoarseningStrategy m_coarsening_strategy = CoarseningStrategy::Sigma;
#endif

**Comment by svater** [comment]
Hi Ann,

thanks a lot for your quick response. I think I understand how you construct the finite element stencil for your nodal Poisson solver, at least on a single-level grid. I am more interest in

1) what happens in case of an AMR grid with different levels. Especially I would like to better understand how you deal with coarse-fine interfaces in case of a composite solve, and where I can find that in the code. 

2) some more implementation details, e.g., what CoarseningStrategy::RAP means.

However, maybe I just have to further iterate on reading your paper and the code :-)

**Comment by asalmgren** [comment]
Stefan,

The coarse-fine stencil comes from the integral formulation of the stencil
-- you integrate over fine cells on the fine side and coarse cells on the
coarse side.

Brandon Runnels has demonstrated that for the stencil he uses, you can
actually compute the coarse/fine stencil by computing the fine residual on
the coarse/fine nodes plus ghost nodes then using the standard
fine-->coarse residual-coarsening procedure.   We haven't yet investigated
if that gives the same results for our nodal stencil (we think it should
...?).

Specifically see
https://amrex-codes.github.io/amrex/docs_html/LinearSolvers.html#multi-component-operators

@weiqun -- can you provide a reference for the RAP coarsening?

**Comment by WeiqunZhang** [comment]
We have two coarsening strategies.  One is called `Sigma` that coarsens the `sigma` coefficient and forms a coarse operator in a geometric way.  The other is called `RAP` that denotes how the coarse operator is formed.  It's formed in an algebraic multgrid way (Galerkin procedure).  That is the coarse A is restriction operator * fine A * prolongation operator, and the restriction operator is the transpose of prolongation.  We use the RAP strategy for EB because in the algebraic way, we don't have to worry about the geometric coarsening of the embedded boundary.

**Comment by svater** [comment]
Thanks a lot for the explanations! 

Still, for the coarse-fine stencil it is not clear to me how your FE basis functions look like. If I look at Fig. 1 of your '98 paper I see that you linearly interpolate at the coarse-fine interface. But which trial/test functions are you using when you are at a corner of a fine grid (e.g. 3rd and 4th row in Fig. 1)? Over which area do you integrate?

I just saw that there are plenty of changes in the MLMG directory in the development branch. It seems that you are abandoning the Fortran kernels in favor of c++ (for GPU optimization?). Is that planned for all kernel functions?

**Comment by WeiqunZhang** [comment]
Yes we are rewriting essentially all Fortran kernels in C++ for GPU.

**Comment by jbbel** [comment]
![image](https://user-images.githubusercontent.com/12703327/65630151-ad266900-df89-11e9-8aba-7be139a0e681.png)

the stencil is constructed as a conforming finite element discretization with bilinear elements

we view the RHS as being piecewise constant on each element

in the above picture, unknowns are at the solid dots
 the 3 course nodes along the middle are the ones with strange basis functions.

For the central node, the basis is the usual bilinear on the two coarse cells.

the function is linear along the edge bounding coarse and fine so 1 at center then 3/4, 1/2, 1/4, 0 moving up or donw
the basis function is also zero at the interior fine nodes and bilinear on each fine cell at the boundary

thus the values at the corners of the fine cells along the boundary are

0      0
.25   0
.5     0
.75   0
1.     0

the basis function is then bilinear on each cell and we just construct the stencil from the weak form

does that make sense?

**Comment by jbbel** [comment]
more . . .

for the more complex configurations, rows 3,4,5 in that figure you do the same thing as in previous email

so support of basis function at center is all cells with an open circle.  stencil from integral of weak form over support of basis functions

**Comment by ajnonaka** [comment]
[NodalStencils.pdf](https://github.com/AMReX-Codes/amrex/files/3654463/NodalStencils.pdf)

Some time ago I wrote some notes on how these derivations are done for my own edification.  The notes unfortunately stop right at the AMR section which I should probably work the details out some day.  The point is if you look at the last figure in this attachment, the basis function is a hat centered at (i,j) that bilinearly goes to zero at the outer nodes of the entire diagram... I think?

**Comment by svater** [comment]
Thanks for all the interesting comments. I think I now understand. In the configurations of rows 3 and 4, the center basis function has also a kink at the fine-fine interfaces of the fine cells adjacent to the center node, right? If someone can point me to the function, where this is computed I would be grateful. Otherwise I will further dig around :-)

Concerning the kernel rewriting thanks for letting me know. Then I will keep an eye on this.
