### ISSUE TITLE
Multi-level Refinement Leaving Holes

### ISSUE THREAD

**Issue by aerojpapp** [AMReX-Codes/amrex#605]
Hello All,

I'm using what I think is a simple test case to examine multi-level refinement.  I have a 101x101 grid with a domain size of 0.5m in X and 0.01m in Y.  Basically, a boundary layer type grid.  The initial Level 0 grid is broken into 4 blocks and I've created my own tagging function that tags a swath of points diagonally across the domain.  If this works, you should see a figure of the Level 0 grid along with the tagging function (blue means tagged, red means no tag)

![Fig01](https://user-images.githubusercontent.com/42849509/67576540-c0556180-f70c-11e9-8052-33c2a9d77212.jpeg)
![Fig02](https://user-images.githubusercontent.com/42849509/67576541-c0556180-f70c-11e9-87b2-1ceab82408a3.jpeg)

The first level of refinement does a pretty good job as seen by the next figure

![Fig03](https://user-images.githubusercontent.com/42849509/67576708-0d393800-f70d-11e9-8aeb-5c33edcb64c4.jpeg)

However, things go wonky at the second level of refinement.

![Fig04](https://user-images.githubusercontent.com/42849509/67576763-2b069d00-f70d-11e9-9666-021771813bcb.jpeg)

These results are after I've commented out the section in MakeNewGrids(Real time) function in AMReX_AmrMesh.cpp that iterates on new grids to ensure that all the interesting 'junk' is encompassed.  In other words, setting the iterate_on_new_grids flag to false.  If I set it to true and do iterate, I get even worse results.  The first level is entirely refined while the second level looks like this:

![Fig05](https://user-images.githubusercontent.com/42849509/67577269-242c5a00-f70e-11e9-9b12-4634bfb8c365.jpeg)

I like to think I'm pretty good at understanding/modifying code, but need some help as to where to start looking to figure out what is going on.  I assume it's somewhere in AmrMesh::MakeNewGrids, but things go plaid after that.

Or has it something to do with my ref_ratio (2), blocking_factor (20), max_grid_size (100), and/or regrid_int (2)?

I'm using release 19.11 out of the trunk.

Any help is appreciated.

Thanks,

John

**Comment by asalmgren** [comment]
John - Would you be willing to share your code and inputs file so we can
look into this?

Sent from my iPhone

On Oct 25, 2019, at 7:11 AM, aerojpapp <notifications@github.com> wrote:

﻿

Hello All,

I'm using what I think is a simple test case to examine multi-level
refinement. I have a 101x101 grid with a domain size of 0.5m in X and 0.01m
in Y. Basically, a boundary layer type grid. The initial Level 0 grid is
broken into 4 blocks and I've created my own tagging function that tags a
swath of points diagonally across the domain. If this works, you should see
a figure of the Level 0 grid along with the tagging function (blue means
tagged, red means no tag)

[image: Fig01]
<https://user-images.githubusercontent.com/42849509/67576540-c0556180-f70c-11e9-8052-33c2a9d77212.jpeg>
[image: Fig02]
<https://user-images.githubusercontent.com/42849509/67576541-c0556180-f70c-11e9-87b2-1ceab82408a3.jpeg>

The first level of refinement does a pretty good job as seen by the next
figure

[image: Fig03]
<https://user-images.githubusercontent.com/42849509/67576708-0d393800-f70d-11e9-8aeb-5c33edcb64c4.jpeg>

However, things go wonky at the second level of refinement.

[image: Fig04]
<https://user-images.githubusercontent.com/42849509/67576763-2b069d00-f70d-11e9-9666-021771813bcb.jpeg>

These results are after I've commented out the section in MakeNewGrids(Real
time) function in AMReX_AmrMesh.cpp that iterates on new grids to ensure
that all the interesting 'junk' is encompassed. In other words, setting the
iterate_on_new_grids flag to false. If I set it to true and do iterate, I
get even worse results. The first level is entirely refined while the
second level looks like this:

[image: Fig05]
<https://user-images.githubusercontent.com/42849509/67577269-242c5a00-f70e-11e9-9b12-4634bfb8c365.jpeg>

I like to think I'm pretty good at understanding/modifying code, but need
some help as to where to start looking to figure out what is going on. I
assume it's somewhere in AmrMesh::MakeNewGrids, but things go plaid after
that.

Or has it something to do with my ref_ratio (2), blocking_factor (20),
max_grid_size (100), and/or regrid_int (2)?

I'm using release 19.11 out of the trunk.

Any help is appreciated.

Thanks,

John

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AMReX-Codes/amrex/issues/605?email_source=notifications&email_token=ACRE6YQGVR3FYPAAGSKI4N3QQL5CHA5CNFSM4JFD4R4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HUMXVTA>,
or unsubscribe

**Comment by asalmgren** [comment]
Also -- you mention the grid is 101x101 but blocking_factor = 20 -- that
wouldn't be ok unless you mean the grid is 100 cells x 100 cells (which is
equivalent to 101 nodes x 101 nodes) -- is that correct?

It's hard to tell from the graphic -- are all your grid in fact divisible
by 20?

It looks like n_error_buf = 1 by default -- have you changed that at all?

Your ref_ratio, max_grid_size and regrid_int are fine.

Ann

**Comment by WeiqunZhang** [comment]
Maybe you can write a simple test code to demonstrate the issue.

**Comment by aerojpapp** [comment]
Ann,

Sorry, the level 0 grid is 401x401 by points.  400x400 by cells.

Some more info that may be important.  The level 0 grid is explicitly partitioned (I overload the box array and distribution mapping during MFab creation) into 4, 100x100 blocks that are spread across 4 parallel nodes.  The level 1 and level 2 box arrays, distribution maps, and MFabs are created through AMReX.  However, not all the level 1 and level 2 cells are divisible by 20, but they are all even.  The maximum size of any refined grid is 100 cells.

I have not changed n_error_buf.  Would it help to increase/decrease?  

Thanks,

John

**Comment by aerojpapp** [comment]
Will be a while before I find time to put together a simple test code.

John

**Comment by asalmgren** [comment]
If they're not divisible by 20 then something is definitely wrong --
blocking_factor = 20 is supposed to explicitly enforce that.

Can you send me the function you use for tagging so I can try to reproduce
locally?

One thing that may be relevant is that the way we enforce blocking factor
is by coarsening the "coarse grid" on which we actually do the grid
creation.

So if I want to create fine grids with blocking factor = 8 for example, I
can coarsen my current "coarse grid" by a factor of 4, create grids there,
then refine them by a factor of 8 to the right "fine level" and they are
guaranteed to be divisible by 8.

But that only works "correctly" if blocking factor is a power of 2 -- I'll
need to think about the implications of it not being a power of 2 (and yes
we will document / disallow it if it does generate this type of behavior!)

Could you try setting blocking_factor = 16 and see if that "just works"?

(BTW -- if what you really intended was no grids bigger than 20 rather than
specifically wanting multiples of 20, you can use max_grid_size instead of
blocking_factor and that should "just work")

Ann

**Comment by aerojpapp** [comment]
Ann,

Brilliant!  I wasn't able to go to 16 because 100 is not divisible by 16 (amrex::Error::0::domain size not divisible by blocking_factor), but I lowered it to 10 and it looks pretty good.  Let me digest your statements a bit more.  I may have an additional question or two.

Level 1

![Fig01](https://user-images.githubusercontent.com/42849509/67605186-9e2f0400-f74b-11e9-9913-0d694a65ff7a.jpeg)

Level 2

![Fig02](https://user-images.githubusercontent.com/42849509/67605196-a6873f00-f74b-11e9-82ac-48f4931d9f7a.jpeg)

**Comment by asalmgren** [comment]
John --

I've tried to reproduce the weird behavior you were seeing but haven't been
able to.

I set the domain to be 400 cells by 400 cells and set the tagging criteria
to be:

  do       k = lo(3), hi(3)
     do    j = lo(2), hi(2)
        do i = lo(1), hi(1)

           x   = (dble(i+.5)) * dx(1)

           yline = 0.5d0 + 0.1 * (x - 0.5)

           ylo   = (dble(j  )) * dx(2)
           yhi   = (dble(j+1)) * dx(2)

           if (yline .gt. ylo .and. yline .lt. yhi) then
              tag(i,j  ,k) = set
           endif

        enddo
     enddo
  enddo

In the inputs file I set

geometry.prob_lo     =  0.0  0.0
geometry.prob_hi     =  1.0  1.0

amr.n_cell           = 400 400
amr.blocking_factor = 20
amr.n_error_buf = 2

If you want to try this yourself to play around, go into
amrex/Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex in your amrex repo.

Modify Prob.f90 to set
           ! Default
           phi(i,j,k) = 0.0

           x     = (dble(i)+.5) * dx(1)
           y     = (dble(j)+.5) * dx(2)

           ylo   = (dble(j  )) * dx(2)
           yhi   = (dble(j+1)) * dx(2)

           yline = 0.5d0 + 0.1 * (x - 0.5)

           if (yline .gt. ylo .and. yline .lt. yhi) then
              phi(i,j  ,k) = 1.0
           endif

The attached picture shows a zoom in of the center region -- the grids look
exactly as expected.    Black is the level 0 grids, light green is level 1
and red is level 2.

Is it possible there's something off in your tagging routine?

Ann

**Comment by asalmgren** [comment]
![phi_ref](https://user-images.githubusercontent.com/10637154/67610962-1d700800-f74b-11e9-8e94-d5dc91405f30.png)

**Comment by asalmgren** [comment]
The more I think about it the more I realize that blocking_factor just does not make sense if it is not a power of 2 (or 1 is ok).    The purpose of it is to enable coarsening for multigrid (by factors of 2), and the way it is achieved is by coarsening the mesh on which we create the grids (by factors of 2).  

John -- if you git pull for amrex your code will now abort if you pass in blocking factor of 10 or 20.  I'll add a comment in the documentation.  The best way to make "larger" / "blockier" grids is to use n_error_buf -- this will ensure that the regions you really want tagged are well into the interior of the refined regions (unlike blocking_factor which will make larger grids but may not keep a c/f boundary away from the tagged cells).    Also be aware that the lower the "grid_eff" the less the gridding algorithm will try to cut the grids so that also will result in larger grids.

**Comment by aerojpapp** [comment]
Did you leave iterate_on_new_grids true?

John

**Comment by asalmgren** [comment]
Good question, I'll need to double-check that.

Unfortunately not until the lab re-opens so it may be a few days ...

**Comment by aerojpapp** [comment]
One last question.  Does the geometry have anything to do with blocking?  The example problem grid size is 0.5m by 0.01m, not the 1x1 you used.

John

**Comment by asalmgren** [comment]
John -- I ran the test with iterate_on_new_grids false then with iterate_on_new_grids true and printed out the grids.   It does exactly what one would expect.   The first time through the level 1 grids cover the tagged regions, but proper nesting doesn't let the level 2 grids cover them.  The iteration procedure grows the level 1 and level 2 grids so that 1) the level 2 grids cover the tagged cells and 2) the level 2 grids are properly nested inside the level 1 grids.

I can't do exactly your problem since you haven't told me what cells you actually tag, but it doesn't appear to be a problem in the AMReX algorithm itself.

**Comment by asalmgren** [comment]
John -- I did a little more testing and in some cases I can get the level 2 grids to not cover the tagged cells when iterate_on_new_grids is false, but that is as expected -- the first time we make level 2 grids they are constrained to be properly nested within level 1 grids so they can't necessarily cover anything.  So this is exactly why we iterate.

I'm happy to try once your exact case more specifically if you'll share your exact tagging criteria in terms of (x,y)

**Comment by aerojpapp** [comment]
Ann,

Thanks for everything.  Just to close things out.  There was a bug in the way I tagged the refinement points.  I also changed my grid size to be a factor of 2.  I'm now always using iterate_on_new_grids (it helped me find the bug with my tagging variable) and things seem to be working.

If you want to try using my exact geometry and refinement condition, the physical size is now 0.64m by 0.0128m with 256 x 256 cells.  My refinement criteria is any cell center between lines y=a(x-x0)+y0 where:

x0=1.13427
y0=0.011073462
a=0.00872688

x0=1.13427
y0=0.009073538
a=0.00872688

The only confusing issues is what to change to get fewer, bigger blocks as opposed to more, smaller blocks?  You were saying that max_grid_size is more appropriate that setting a large blocking_factor.  I'm also using (for better or worse) the FORTRAN interface.  To set n_error_buf, I'm using:

call amrex_parmparse_build(pp,"amr")
call pp%addarr("n_error_buf", [2, 2, 2, 2, 2])

I believe this sets n_error_buf in all directions to 2 down to level 5.  Do you have to set the in powers of 2?  I didn't see that much of a difference setting it to 1 or 2 or even 3 so I'm wondering if I'm using it wrong.

Thanks,

John

**Comment by WeiqunZhang** [comment]
Increasing `amr.blocking_factor` will give fewer, bigger blocks.  All boxes' lower and upper (+1) bounds are multiples of the blocking factor.
