### ISSUE TITLE
Want to communicate more that 2 GByte

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#642]
`AMReX_FabArrayCommI.H` contains this line:
```
BL_ASSERT(nbytes < std::size_t(std::numeric_limits<int>::max()));
```
On systems with 250 GByte of memory it's easy to want to communicate more than 2 GByte of data. This should either be possible, or AMReX should always check for this and abort.

**Comment by eschnett** [comment]
[BigMPI](https://github.com/jeffhammond/BigMPI)?

**Comment by atmyers** [comment]
We can also use unsigned long long as the type instead of char to send more than max int bytes.

**Comment by WeiqunZhang** [comment]
As Andrew has said, we could use unsigned long long as the type for MPI.  That could make it able to communicate up to 16 GB.  We have been talking about this.  Since you have a need for it, we will try to do this quickly.

If it's important for you to be able to communicate more than 16 GB, let us know.

**Comment by eschnett** [comment]
At the moment I have a work-around to use fewer OpenMP threads and more MPI processes per node, which avoids the issue. I don't know yet whether I'll need to communicate more than 16 GByte in the future; this depends on how many OpenMP threads people use.

**Comment by WeiqunZhang** [comment]
I added support for up to 128 GB to the development branch. @eschnett   Could you run some tests to see if it works for you?  It uses unsigned long long if the size of the data is between 2GB and 16 GB, and a derived type of 8 unsigned long longs if the size is between 16 and 128 GB.  So it would be great if the tests can cover both ranges.

**Comment by eschnett** [comment]
I have run some tests, and things seem to be working for me. However, I don't know whether my tests covered both ranges.

Looking at the code, I see that you use integer division to calculate the number of elements to transfer. This truncates by default, so if the message size is not a multiple of the transfer data type size, some data will be missing.

**Comment by WeiqunZhang** [comment]
Could you be more specific about which line?

**Comment by WeiqunZhang** [comment]
I see.  I think you are talking about lines like

https://github.com/AMReX-Codes/amrex/blob/development/Src/Base/AMReX_FabArrayCommI.H#L188

I think that's OK because send_size is guaranteed to be multiple of sizeof unsigned long long by 

https://github.com/AMReX-Codes/amrex/blob/development/Src/Base/AMReX_FabArrayCommI.H#L124

**Comment by eschnett** [comment]
Yes I was...
