### ISSUE TITLE
Questions about the examples of using Multigrid Solver in amrex

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#94]
Hello all,

In the directory /Src/LinearSolvers/F_MG, there are two kinds of MG solver. I noticed some theoretical explanation in the Chapter 22 of MAESTRO guide, yet I still do not know how to use the codes. Are there some good examples for teaching how to use these solvers?

To be more specific, suppose the cell centered pressure value and edge centered velocities value have been defined on a Multifab, how to use these solvers to solve Poisson equation, like the following form:

![picture1](https://user-images.githubusercontent.com/30739800/29586839-997dd3da-8751-11e7-8311-60001da9af47.png)

Best and thanks!

**Comment by zingale** [comment]
in Maestro, that type of equation with edge-centered velocities is solved by `macproject.f90`.  Note that uses the Fortran version of AMReX.

**Comment by ruihai0925** [comment]
Thanks zingale.

So I need to use the fortran driven version of amrex, like the example  Advection_F.

**Comment by zingale** [comment]
I only pointed to that since you mentioned Maestro, which currently is based on the Fortran source tree.

If you want to use the C++ source tree, then you can look at IAMR, which also has a MAC projection of that form:

https://github.com/AMReX-Codes/IAMR/blob/master/Source/MacProj.cpp

**Comment by ruihai0925** [comment]
Thanks so much.

I will try to understand these two different source trees and choose a proper one.

Best.

**Comment by ruihai0925** [comment]
@zingale 

Hello zingale, here is an issue about fortran driven code in the amrex-master/Tutorials/Amr/Advection_F example.

While digging out the amrex_fillpatch function, I thought it does not fill the ghost cell values for physical boundary. I mean, it only fills the ghost cells of the same level or coarse-fine boundary. Is it correct?

If it is correct, I saw the codes:

![image](https://user-images.githubusercontent.com/30739800/29638882-559b25a0-881e-11e7-94c7-dbb70e2d218e.png)

In my view, I think the lo_bc and hi_bc defined here should not be used in the amrex_fillpatch since it should be used for physical boundary condition. I am not sure if my understandings are correct or not.

Thanks and best!
